/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AmbientesBriefingSchema extends BaseModel {
  static $columns = ['briefingId', 'createdAt', 'descricao', 'id', 'medidasPreliminares', 'observacoesEspecificas', 'tipo', 'updatedAt'] as const
  $columns = AmbientesBriefingSchema.$columns
  @column()
  declare briefingId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descricao: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare medidasPreliminares: string | null
  @column()
  declare observacoesEspecificas: string | null
  @column()
  declare tipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ArquitetoSchema extends BaseModel {
  static $columns = ['consultorId', 'createdAt', 'email', 'enderecoEscritorio', 'escritorio', 'especialidade', 'id', 'isActive', 'nivelParceria', 'nome', 'statusCarteira', 'telefone', 'tipo', 'updatedAt'] as const
  $columns = ArquitetoSchema.$columns
  @column()
  declare consultorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare enderecoEscritorio: string | null
  @column()
  declare escritorio: string | null
  @column()
  declare especialidade: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare nivelParceria: string
  @column()
  declare nome: string
  @column()
  declare statusCarteira: string
  @column()
  declare telefone: string | null
  @column()
  declare tipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BriefingSchema extends BaseModel {
  static $columns = ['ambientes', 'arquitetoEmail', 'arquitetoNome', 'arquitetoTelefone', 'cidadeObra', 'createdAt', 'enderecoObra', 'enviadoEm', 'estadoObra', 'estiloPreferido', 'faixaInvestimentoMax', 'faixaInvestimentoMin', 'id', 'motivoDevolucao', 'observacoes', 'prazoDesejado', 'projetoId', 'referenciasUrl', 'score', 'scoreDetalhes', 'scoreMinimo', 'status', 'updatedAt'] as const
  $columns = BriefingSchema.$columns
  @column()
  declare ambientes: any | null
  @column()
  declare arquitetoEmail: string | null
  @column()
  declare arquitetoNome: string | null
  @column()
  declare arquitetoTelefone: string | null
  @column()
  declare cidadeObra: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enderecoObra: string | null
  @column.dateTime()
  declare enviadoEm: DateTime | null
  @column()
  declare estadoObra: string | null
  @column()
  declare estiloPreferido: string | null
  @column()
  declare faixaInvestimentoMax: string | null
  @column()
  declare faixaInvestimentoMin: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motivoDevolucao: string | null
  @column()
  declare observacoes: string | null
  @column()
  declare prazoDesejado: string | null
  @column()
  declare projetoId: number
  @column()
  declare referenciasUrl: any | null
  @column()
  declare score: string
  @column()
  declare scoreDetalhes: any | null
  @column()
  declare scoreMinimo: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CargoSchema extends BaseModel {
  static $columns = ['ativo', 'createdAt', 'departamentoId', 'id', 'nome', 'updatedAt'] as const
  $columns = CargoSchema.$columns
  @column()
  declare ativo: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare departamentoId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClienteSchema extends BaseModel {
  static $columns = ['arquitetoId', 'cadastroAprovado', 'cadastroAprovadoEm', 'cadastroAprovadoPor', 'cpfCnpj', 'createdAt', 'email', 'id', 'isActive', 'nome', 'observacoes', 'profissaoRamo', 'rgIe', 'telefone', 'tipo', 'updatedAt'] as const
  $columns = ClienteSchema.$columns
  @column()
  declare arquitetoId: number | null
  @column()
  declare cadastroAprovado: boolean
  @column.dateTime()
  declare cadastroAprovadoEm: DateTime | null
  @column()
  declare cadastroAprovadoPor: number | null
  @column()
  declare cpfCnpj: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare nome: string
  @column()
  declare observacoes: string | null
  @column()
  declare profissaoRamo: string | null
  @column()
  declare rgIe: string | null
  @column()
  declare telefone: string
  @column()
  declare tipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ColaboradoreSchema extends BaseModel {
  static $columns = ['agencia', 'banco', 'cargaHoraria', 'cargoId', 'conta', 'cpf', 'createdAt', 'dataAdmissao', 'dataDesligamento', 'dataNascimento', 'dataVigenciaSalario', 'departamentoId', 'emailCorporativo', 'emailPessoal', 'enderecoBairro', 'enderecoCep', 'enderecoCidade', 'enderecoComplemento', 'enderecoEstado', 'enderecoLogradouro', 'enderecoNumero', 'entrevistaSaida', 'escala', 'estadoCivil', 'fotoUrl', 'gestorId', 'id', 'isActive', 'jornadaEspecial', 'modalidade', 'motivoDesligamento', 'nome', 'observacoesComportamentais', 'perfilDiscPrimario', 'perfilDiscSecundario', 'pjCnpj', 'pjContratoUrl', 'pjValorMensal', 'pjVigenciaFim', 'pjVigenciaInicio', 'regime', 'remuneracaoComplementar', 'rg', 'salarioClt', 'sexo', 'telefoneCorporativo', 'telefonePessoal', 'tipoConta', 'tipoContrato', 'tipoDesligamento', 'updatedAt', 'userId'] as const
  $columns = ColaboradoreSchema.$columns
  @column()
  declare agencia: string | null
  @column()
  declare banco: string | null
  @column()
  declare cargaHoraria: string | null
  @column()
  declare cargoId: number
  @column()
  declare conta: string | null
  @column()
  declare cpf: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dataAdmissao: DateTime
  @column.date()
  declare dataDesligamento: DateTime | null
  @column.date()
  declare dataNascimento: DateTime | null
  @column.date()
  declare dataVigenciaSalario: DateTime | null
  @column()
  declare departamentoId: number
  @column()
  declare emailCorporativo: string | null
  @column()
  declare emailPessoal: string | null
  @column()
  declare enderecoBairro: string | null
  @column()
  declare enderecoCep: string | null
  @column()
  declare enderecoCidade: string | null
  @column()
  declare enderecoComplemento: string | null
  @column()
  declare enderecoEstado: string | null
  @column()
  declare enderecoLogradouro: string | null
  @column()
  declare enderecoNumero: string | null
  @column()
  declare entrevistaSaida: string | null
  @column()
  declare escala: string | null
  @column()
  declare estadoCivil: string | null
  @column()
  declare fotoUrl: string | null
  @column()
  declare gestorId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare jornadaEspecial: string | null
  @column()
  declare modalidade: string | null
  @column()
  declare motivoDesligamento: string | null
  @column()
  declare nome: string
  @column()
  declare observacoesComportamentais: string | null
  @column()
  declare perfilDiscPrimario: string | null
  @column()
  declare perfilDiscSecundario: string | null
  @column()
  declare pjCnpj: string | null
  @column()
  declare pjContratoUrl: string | null
  @column()
  declare pjValorMensal: string | null
  @column.date()
  declare pjVigenciaFim: DateTime | null
  @column.date()
  declare pjVigenciaInicio: DateTime | null
  @column()
  declare regime: string
  @column()
  declare remuneracaoComplementar: string | null
  @column()
  declare rg: string | null
  @column()
  declare salarioClt: string | null
  @column()
  declare sexo: string | null
  @column()
  declare telefoneCorporativo: string | null
  @column()
  declare telefonePessoal: string | null
  @column()
  declare tipoConta: string | null
  @column()
  declare tipoContrato: string | null
  @column()
  declare tipoDesligamento: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class ConcorrentesArquitetoSchema extends BaseModel {
  static $columns = ['arquitetoId', 'createdAt', 'id', 'nomeConcorrente', 'observacoes', 'percentualFechamentoEstimado', 'registradoPorId', 'updatedAt'] as const
  $columns = ConcorrentesArquitetoSchema.$columns
  @column()
  declare arquitetoId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nomeConcorrente: string
  @column()
  declare observacoes: string | null
  @column()
  declare percentualFechamentoEstimado: string
  @column()
  declare registradoPorId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ConfigWipProjetistaSchema extends BaseModel {
  static $columns = ['ativo', 'createdAt', 'id', 'projetistaId', 'updatedAt', 'wipLimit'] as const
  $columns = ConfigWipProjetistaSchema.$columns
  @column()
  declare ativo: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projetistaId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wipLimit: number
}

export class DecisoresArquitetoSchema extends BaseModel {
  static $columns = ['arquitetoId', 'cargo', 'createdAt', 'email', 'id', 'isPrincipal', 'nome', 'observacoes', 'telefone', 'updatedAt'] as const
  $columns = DecisoresArquitetoSchema.$columns
  @column()
  declare arquitetoId: number
  @column()
  declare cargo: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPrincipal: boolean
  @column()
  declare nome: string
  @column()
  declare observacoes: string | null
  @column()
  declare telefone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DepartamentoSchema extends BaseModel {
  static $columns = ['ativo', 'createdAt', 'id', 'nome', 'updatedAt'] as const
  $columns = DepartamentoSchema.$columns
  @column()
  declare ativo: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DocumentosColaboradoreSchema extends BaseModel {
  static $columns = ['colaboradorId', 'createdAt', 'dataVencimento', 'id', 'tipo', 'url'] as const
  $columns = DocumentosColaboradoreSchema.$columns
  @column()
  declare colaboradorId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dataVencimento: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tipo: string
  @column()
  declare url: string
}

export class EnderecosClienteSchema extends BaseModel {
  static $columns = ['bairro', 'cep', 'cidade', 'clienteId', 'complemento', 'createdAt', 'estado', 'id', 'identificacao', 'isPrincipal', 'logradouro', 'numero', 'pontoReferencia', 'tipo', 'updatedAt'] as const
  $columns = EnderecosClienteSchema.$columns
  @column()
  declare bairro: string | null
  @column()
  declare cep: string | null
  @column()
  declare cidade: string
  @column()
  declare clienteId: number
  @column()
  declare complemento: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare estado: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identificacao: string | null
  @column()
  declare isPrincipal: boolean
  @column()
  declare logradouro: string
  @column()
  declare numero: string
  @column()
  declare pontoReferencia: string | null
  @column()
  declare tipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FechamentoSchema extends BaseModel {
  static $columns = ['cadastroAprovado', 'cadastroAprovadoPorId', 'cadernoComercialUrl', 'checklistCompleto', 'checklistJson', 'contratoAssinadoEm', 'contratoUrl', 'createdAt', 'dataFechamento', 'dataLimiteAssinatura', 'id', 'onboardingDisparado', 'onboardingDisparadoEm', 'projetoId', 'updatedAt', 'valorTotalFechamento'] as const
  $columns = FechamentoSchema.$columns
  @column()
  declare cadastroAprovado: boolean
  @column()
  declare cadastroAprovadoPorId: number | null
  @column()
  declare cadernoComercialUrl: string | null
  @column()
  declare checklistCompleto: boolean
  @column()
  declare checklistJson: string | null
  @column.dateTime()
  declare contratoAssinadoEm: DateTime | null
  @column()
  declare contratoUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dataFechamento: DateTime | null
  @column.date()
  declare dataLimiteAssinatura: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare onboardingDisparado: boolean
  @column.dateTime()
  declare onboardingDisparadoEm: DateTime | null
  @column()
  declare projetoId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare valorTotalFechamento: string | null
}

export class FilaProjetoSchema extends BaseModel {
  static $columns = ['createdAt', 'dataAlocacao', 'dataEntradaFila', 'id', 'prioridade', 'projetistaId', 'projetoId', 'status', 'updatedAt'] as const
  $columns = FilaProjetoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dataAlocacao: DateTime | null
  @column.dateTime()
  declare dataEntradaFila: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare prioridade: number
  @column()
  declare projetistaId: number | null
  @column()
  declare projetoId: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class HandoffSchema extends BaseModel {
  static $columns = ['checklistCompleto', 'checklistJson', 'createdAt', 'id', 'liberadoEm', 'liberadoPorId', 'observacoes', 'projetoId', 'updatedAt'] as const
  $columns = HandoffSchema.$columns
  @column()
  declare checklistCompleto: boolean
  @column()
  declare checklistJson: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare liberadoEm: DateTime | null
  @column()
  declare liberadoPorId: number | null
  @column()
  declare observacoes: string | null
  @column()
  declare projetoId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class HistoricoCargoColaboradoreSchema extends BaseModel {
  static $columns = ['aprovadoPorId', 'cargoAnteriorId', 'cargoNovoId', 'colaboradorId', 'createdAt', 'data', 'id', 'justificativa'] as const
  $columns = HistoricoCargoColaboradoreSchema.$columns
  @column()
  declare aprovadoPorId: number
  @column()
  declare cargoAnteriorId: number | null
  @column()
  declare cargoNovoId: number
  @column()
  declare colaboradorId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare data: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare justificativa: string | null
}

export class HistoricoDonoArquitetoSchema extends BaseModel {
  static $columns = ['alteradoPorId', 'arquitetoId', 'consultorAnteriorId', 'consultorNovoId', 'createdAt', 'id', 'motivo'] as const
  $columns = HistoricoDonoArquitetoSchema.$columns
  @column()
  declare alteradoPorId: number | null
  @column()
  declare arquitetoId: number
  @column()
  declare consultorAnteriorId: number | null
  @column()
  declare consultorNovoId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motivo: string | null
}

export class HistoricoSalarialColaboradoreSchema extends BaseModel {
  static $columns = ['colaboradorId', 'createdAt', 'dataVigencia', 'id', 'motivo', 'registradoPorId', 'remuneracaoComplementar', 'salarioClt'] as const
  $columns = HistoricoSalarialColaboradoreSchema.$columns
  @column()
  declare colaboradorId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dataVigencia: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motivo: string
  @column()
  declare registradoPorId: number
  @column()
  declare remuneracaoComplementar: string | null
  @column()
  declare salarioClt: string
}

export class HistoricoStatusLeadSchema extends BaseModel {
  static $columns = ['alteradoPorId', 'createdAt', 'id', 'leadId', 'observacao', 'statusDe', 'statusPara', 'tempoPermanenciaSegundos'] as const
  $columns = HistoricoStatusLeadSchema.$columns
  @column()
  declare alteradoPorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leadId: number
  @column()
  declare observacao: string | null
  @column()
  declare statusDe: string | null
  @column()
  declare statusPara: string
  @column()
  declare tempoPermanenciaSegundos: number | null
}

export class HistoricoStatusProjetoSchema extends BaseModel {
  static $columns = ['alteradoPorId', 'createdAt', 'id', 'observacao', 'projetoId', 'statusDe', 'statusPara'] as const
  $columns = HistoricoStatusProjetoSchema.$columns
  @column()
  declare alteradoPorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare observacao: string | null
  @column()
  declare projetoId: number
  @column()
  declare statusDe: string | null
  @column()
  declare statusPara: string
}

export class InteracoesArquitetoSchema extends BaseModel {
  static $columns = ['arquitetoId', 'createdAt', 'data', 'id', 'leadId', 'responsavelId', 'resumo', 'tipo', 'updatedAt'] as const
  $columns = InteracoesArquitetoSchema.$columns
  @column()
  declare arquitetoId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare data: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leadId: number | null
  @column()
  declare responsavelId: number
  @column()
  declare resumo: string
  @column()
  declare tipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InteracoesLeadSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'leadId', 'responsavelId', 'resumo', 'tipo'] as const
  $columns = InteracoesLeadSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leadId: number
  @column()
  declare responsavelId: number
  @column()
  declare resumo: string
  @column()
  declare tipo: string
}

export class LeadSchema extends BaseModel {
  static $columns = ['ambientesInteresse', 'arquitetoId', 'campanha', 'cidade', 'clienteId', 'concorrentePerdido', 'convertidoEmCliente', 'createdAt', 'decisorPresente', 'email', 'estado', 'faixaOrcamento', 'id', 'motivoDesqualificacao', 'motivoPerda', 'nome', 'orcamentoEstimado', 'origem', 'possuiArquiteto', 'prazoObra', 'qualificado', 'qualificadoEm', 'qualificadoPorId', 'statusAlteradoEm', 'statusFunil', 'telefone', 'tipoImovel', 'ultimaInteracaoEm', 'updatedAt', 'vendedorId'] as const
  $columns = LeadSchema.$columns
  @column()
  declare ambientesInteresse: any | null
  @column()
  declare arquitetoId: number | null
  @column()
  declare campanha: string | null
  @column()
  declare cidade: string | null
  @column()
  declare clienteId: number | null
  @column()
  declare concorrentePerdido: string | null
  @column()
  declare convertidoEmCliente: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare decisorPresente: boolean
  @column()
  declare email: string | null
  @column()
  declare estado: string | null
  @column()
  declare faixaOrcamento: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motivoDesqualificacao: string | null
  @column()
  declare motivoPerda: string | null
  @column()
  declare nome: string
  @column()
  declare orcamentoEstimado: string | null
  @column()
  declare origem: string
  @column()
  declare possuiArquiteto: boolean
  @column()
  declare prazoObra: string | null
  @column()
  declare qualificado: boolean
  @column.dateTime()
  declare qualificadoEm: DateTime | null
  @column()
  declare qualificadoPorId: number | null
  @column.dateTime()
  declare statusAlteradoEm: DateTime | null
  @column()
  declare statusFunil: string
  @column()
  declare telefone: string
  @column()
  declare tipoImovel: string | null
  @column.dateTime()
  declare ultimaInteracaoEm: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vendedorId: number | null
}

export class MetasVisitasConsultorSchema extends BaseModel {
  static $columns = ['configuradoPorId', 'consultorId', 'createdAt', 'id', 'metaVisitasMes', 'updatedAt'] as const
  $columns = MetasVisitasConsultorSchema.$columns
  @column()
  declare configuradoPorId: number | null
  @column()
  declare consultorId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metaVisitasMes: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ParcelaSchema extends BaseModel {
  static $columns = ['comprovanteUrl', 'createdAt', 'dataPagamento', 'fechamentoId', 'formaPagamento', 'id', 'numero', 'observacoes', 'status', 'updatedAt', 'valor', 'vencimento'] as const
  $columns = ParcelaSchema.$columns
  @column()
  declare comprovanteUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dataPagamento: DateTime | null
  @column()
  declare fechamentoId: number
  @column()
  declare formaPagamento: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare numero: number
  @column()
  declare observacoes: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare valor: string
  @column.date()
  declare vencimento: DateTime
}

export class ProjetoSchema extends BaseModel {
  static $columns = ['alertaParado', 'arquitetoId', 'arquitetoNome', 'arquivado', 'arquivadoMotivo', 'clienteId', 'clienteNome', 'codigo', 'conferenteId', 'createdAt', 'id', 'leadId', 'prazoEntregaEstimado', 'projetistaId', 'status', 'statusAlteradoEm', 'updatedAt', 'valorContrato', 'vendedorId'] as const
  $columns = ProjetoSchema.$columns
  @column()
  declare alertaParado: boolean
  @column()
  declare arquitetoId: number | null
  @column()
  declare arquitetoNome: string | null
  @column()
  declare arquivado: boolean
  @column()
  declare arquivadoMotivo: string | null
  @column()
  declare clienteId: number | null
  @column()
  declare clienteNome: string
  @column()
  declare codigo: string
  @column()
  declare conferenteId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leadId: number | null
  @column.date()
  declare prazoEntregaEstimado: DateTime | null
  @column()
  declare projetistaId: number | null
  @column()
  declare status: string
  @column.dateTime()
  declare statusAlteradoEm: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare valorContrato: string | null
  @column()
  declare vendedorId: number | null
}

export class ProjetosComerciaiSchema extends BaseModel {
  static $columns = ['arquivoUrl', 'createdAt', 'criadoPorId', 'descricaoAlteracao', 'id', 'motivoDevolucao', 'numeroApresentacao', 'projetoId', 'renderUrls', 'status', 'submetidoParaValidacaoEm', 'updatedAt', 'validadoEm', 'validadoPorId', 'versao'] as const
  $columns = ProjetosComerciaiSchema.$columns
  @column()
  declare arquivoUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare criadoPorId: number | null
  @column()
  declare descricaoAlteracao: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motivoDevolucao: string | null
  @column()
  declare numeroApresentacao: number
  @column()
  declare projetoId: number
  @column()
  declare renderUrls: string | null
  @column()
  declare status: string
  @column.dateTime()
  declare submetidoParaValidacaoEm: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare validadoEm: DateTime | null
  @column()
  declare validadoPorId: number | null
  @column()
  declare versao: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'isActive', 'isSuperuser', 'nome', 'password', 'perfil', 'telefone', 'ultimoLogin', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isSuperuser: boolean
  @column()
  declare nome: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare perfil: any
  @column()
  declare telefone: string | null
  @column.dateTime()
  declare ultimoLogin: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
