/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Arquitetos: () => import('#controllers/arquitetos_controller'),
  Briefings: () => import('#controllers/briefings_controller'),
  Clientes: () => import('#controllers/clientes_controller'),
  Colaboradores: () => import('#controllers/colaboradores_controller'),
  Configuracoes: () => import('#controllers/configuracoes_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Fechamentos: () => import('#controllers/fechamentos_controller'),
  Fila: () => import('#controllers/fila_controller'),
  Leads: () => import('#controllers/leads_controller'),
  Projetos: () => import('#controllers/projetos_controller'),
  Session: () => import('#controllers/session_controller'),
}
