"""frente a leads: fila atendimento, config, criado_por_id

Revision ID: 80d885a38d2f
Revises: f0d1e904df6f
Create Date: 2026-07-21 21:59:35.468476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d885a38d2f'
down_revision: Union[str, None] = 'f0d1e904df6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE origemlead ADD VALUE IF NOT EXISTS 'WHATSAPP'")
    op.execute("ALTER TYPE origemlead ADD VALUE IF NOT EXISTS 'TELEFONE'")
    op.execute("ALTER TYPE tipointeracaoarquiteto ADD VALUE IF NOT EXISTS 'INDICACAO_LEAD'")
    op.execute("ALTER TYPE tiponotificacao ADD VALUE IF NOT EXISTS 'LEAD_AGUARDANDO_ESCALONADO'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_fila_atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minutos_alerta', sa.Integer(), nullable=False),
    sa.Column('minutos_escalonamento', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_fila_atendimento_id'), 'config_fila_atendimento', ['id'], unique=False)
    op.create_table('fila_atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('motivo_indisponivel_categoria', sa.Enum('ATENDIMENTO_MARCADO', 'ORCAMENTO_PEDIDO', 'ALMOCO', 'OUTRO', name='motivoindisponibilidade'), nullable=True),
    sa.Column('motivo_indisponivel_obs', sa.Text(), nullable=True),
    sa.Column('checkin_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo_hoje', sa.Boolean(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendedor_id')
    )
    op.create_index(op.f('ix_fila_atendimento_id'), 'fila_atendimento', ['id'], unique=False)
    op.add_column('leads', sa.Column('criado_por_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'users', ['criado_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ALTER TYPE ... DROP VALUE não existe no Postgres; reverter os valores de enum
    # adicionados no upgrade() exigiria recriar o tipo inteiro. Não implementado —
    # downgrade desta revisão cobre só as tabelas/colunas novas.
    op.drop_column('leads', 'criado_por_id')
    op.drop_table('config_fila_atendimento')
    op.drop_table('fila_atendimento')
