"""schema inicial completo

Revision ID: 94d29e691390
Revises: 
Create Date: 2026-07-28 22:33:12.417786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d29e691390'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departamentos_id'), 'departamentos', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('perfil', sa.Enum('DIRETORIA', 'GERENTE_COMERCIAL', 'VENDEDOR', 'RECEPCAO', 'PROJETISTA', 'CONFERENTE', 'SUPERVISOR_MONTAGEM', 'GESTOR_LOGISTICA', 'SAC', 'FINANCEIRO', 'MONTADOR_PROPRIO', 'MONTADOR_TERCEIRO', 'ARQUITETO', 'RH', 'CLIENTE', name='perfilusuario'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('arquitetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('escritorio', sa.String(length=200), nullable=True),
    sa.Column('endereco_escritorio', sa.String(length=300), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('nivel_parceria', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.Enum('ARQUITETO', 'DESIGNER_INTERIORES', 'DECORADOR', 'ENGENHEIRO', 'CORRETOR', 'OUTRO', name='tipoespecificador'), nullable=False),
    sa.Column('especialidade', sa.String(length=200), nullable=True),
    sa.Column('consultor_id', sa.Integer(), nullable=True),
    sa.Column('status_carteira', sa.Enum('ATIVO', 'EM_PROSPECCAO', 'INATIVO', name='statuscarteiraespecificador'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consultor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_arquitetos_id'), 'arquitetos', ['id'], unique=False)
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargos_id'), 'cargos', ['id'], unique=False)
    op.create_table('config_wip_projetistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projetista_id', sa.Integer(), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['projetista_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projetista_id')
    )
    op.create_index(op.f('ix_config_wip_projetistas_id'), 'config_wip_projetistas', ['id'], unique=False)
    op.create_table('metas_visitas_consultor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('meta_visitas_mes', sa.Integer(), nullable=False),
    sa.Column('configurado_por_id', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['configurado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['consultor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consultor_id')
    )
    op.create_index(op.f('ix_metas_visitas_consultor_id'), 'metas_visitas_consultor', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('tipo', sa.Enum('PESSOA_FISICA', 'PESSOA_JURIDICA', name='tipocliente'), nullable=True),
    sa.Column('cadastro_aprovado', sa.Boolean(), nullable=True),
    sa.Column('cadastro_aprovado_por', sa.Integer(), nullable=True),
    sa.Column('cadastro_aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arquiteto_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['cadastro_aprovado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('estado_civil', sa.String(length=30), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('perfil_disc_primario', sa.String(length=20), nullable=True),
    sa.Column('perfil_disc_secundario', sa.String(length=20), nullable=True),
    sa.Column('observacoes_comportamentais', sa.Text(), nullable=True),
    sa.Column('telefone_pessoal', sa.String(length=20), nullable=True),
    sa.Column('telefone_corporativo', sa.String(length=20), nullable=True),
    sa.Column('email_pessoal', sa.String(length=200), nullable=True),
    sa.Column('email_corporativo', sa.String(length=200), nullable=True),
    sa.Column('endereco_logradouro', sa.String(length=300), nullable=True),
    sa.Column('endereco_numero', sa.String(length=20), nullable=True),
    sa.Column('endereco_complemento', sa.String(length=100), nullable=True),
    sa.Column('endereco_bairro', sa.String(length=100), nullable=True),
    sa.Column('endereco_cidade', sa.String(length=100), nullable=True),
    sa.Column('endereco_estado', sa.String(length=2), nullable=True),
    sa.Column('endereco_cep', sa.String(length=10), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('regime', sa.Enum('CLT', 'PJ', name='regimecontratacao'), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=100), nullable=True),
    sa.Column('pj_cnpj', sa.String(length=20), nullable=True),
    sa.Column('pj_contrato_url', sa.String(length=500), nullable=True),
    sa.Column('pj_valor_mensal', sa.Float(), nullable=True),
    sa.Column('pj_vigencia_inicio', sa.Date(), nullable=True),
    sa.Column('pj_vigencia_fim', sa.Date(), nullable=True),
    sa.Column('salario_clt', sa.Float(), nullable=True),
    sa.Column('remuneracao_complementar', sa.Float(), nullable=True),
    sa.Column('data_vigencia_salario', sa.Date(), nullable=True),
    sa.Column('carga_horaria', sa.String(length=50), nullable=True),
    sa.Column('escala', sa.String(length=100), nullable=True),
    sa.Column('modalidade', sa.Enum('PRESENCIAL', 'HIBRIDO', 'REMOTO', name='modalidadetrabalho'), nullable=True),
    sa.Column('jornada_especial', sa.String(length=200), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('conta', sa.String(length=20), nullable=True),
    sa.Column('tipo_conta', sa.String(length=20), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('data_desligamento', sa.Date(), nullable=True),
    sa.Column('tipo_desligamento', sa.String(length=50), nullable=True),
    sa.Column('motivo_desligamento', sa.Text(), nullable=True),
    sa.Column('entrevista_saida', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['gestor_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colaboradores_cpf'), 'colaboradores', ['cpf'], unique=True)
    op.create_index(op.f('ix_colaboradores_id'), 'colaboradores', ['id'], unique=False)
    op.create_table('concorrentes_arquitetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquiteto_id', sa.Integer(), nullable=False),
    sa.Column('nome_concorrente', sa.String(length=200), nullable=False),
    sa.Column('percentual_fechamento_estimado', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concorrentes_arquitetos_id'), 'concorrentes_arquitetos', ['id'], unique=False)
    op.create_table('decisores_arquitetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquiteto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('is_principal', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisores_arquitetos_id'), 'decisores_arquitetos', ['id'], unique=False)
    op.create_table('historico_dono_arquitetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquiteto_id', sa.Integer(), nullable=False),
    sa.Column('consultor_anterior_id', sa.Integer(), nullable=True),
    sa.Column('consultor_novo_id', sa.Integer(), nullable=False),
    sa.Column('alterado_por_id', sa.Integer(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alterado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['consultor_anterior_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['consultor_novo_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_dono_arquitetos_id'), 'historico_dono_arquitetos', ['id'], unique=False)
    op.create_table('documentos_colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_colaboradores_id'), 'documentos_colaboradores', ['id'], unique=False)
    op.create_table('historico_cargo_colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('cargo_anterior_id', sa.Integer(), nullable=True),
    sa.Column('cargo_novo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('aprovado_por_id', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cargo_anterior_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['cargo_novo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_cargo_colaboradores_id'), 'historico_cargo_colaboradores', ['id'], unique=False)
    op.create_table('historico_salarial_colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('salario_clt', sa.Float(), nullable=False),
    sa.Column('remuneracao_complementar', sa.Float(), nullable=True),
    sa.Column('data_vigencia', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_salarial_colaboradores_id'), 'historico_salarial_colaboradores', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('origem', sa.Enum('INSTAGRAM', 'INDICACAO', 'SITE_GOOGLE', 'CONSTRUTORA', 'SHOWROOM', 'ARQUITETO', 'OUTRO', name='origemlead'), nullable=False),
    sa.Column('campanha', sa.String(length=200), nullable=True),
    sa.Column('status_funil', sa.Enum('NOVO_LEAD', 'QUALIFICANDO', 'EM_VISITA', 'EM_BRIEFING', 'EM_PROJETO', 'EM_NEGOCIACAO', 'FECHADO', 'PERDIDO', 'DESQUALIFICADO', name='statusfunil'), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('arquiteto_id', sa.Integer(), nullable=True),
    sa.Column('qualificado', sa.Boolean(), nullable=True),
    sa.Column('motivo_perda', sa.Text(), nullable=True),
    sa.Column('concorrente_perdido', sa.String(length=200), nullable=True),
    sa.Column('convertido_em_cliente', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_interacao_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('projetista_id', sa.Integer(), nullable=True),
    sa.Column('conferente_id', sa.Integer(), nullable=True),
    sa.Column('arquiteto_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOVO_LEAD', 'QUALIFICANDO', 'EM_VISITA', 'EM_BRIEFING', 'NA_FILA', 'EM_PROJETO', 'AGUARD_VALIDACAO', 'EM_RENDER', 'AGUARD_APRESENTACAO', 'EM_AJUSTE', 'EM_FECHAMENTO', 'AGUARD_ASSINATURA', 'EM_HANDOFF', 'CONTATO_CONF', 'VALIDANDO_OBRA', 'EM_MEDICAO', 'EM_ADEQUACAO', 'ALINHANDO_CLIENTE', 'EM_AUDITORIA', 'AGUARD_ASSINATURA_TEC', 'EM_PRODUCAO', 'PRE_MONTAGEM', 'AGUARD_MERCADORIA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'EM_MONTAGEM', 'COM_OCORRENCIA', 'CHECKLIST_FINAL', 'POS_VENDA', 'EM_AT', 'RELACIONAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusprojeto'), nullable=True),
    sa.Column('status_anterior', sa.Enum('NOVO_LEAD', 'QUALIFICANDO', 'EM_VISITA', 'EM_BRIEFING', 'NA_FILA', 'EM_PROJETO', 'AGUARD_VALIDACAO', 'EM_RENDER', 'AGUARD_APRESENTACAO', 'EM_AJUSTE', 'EM_FECHAMENTO', 'AGUARD_ASSINATURA', 'EM_HANDOFF', 'CONTATO_CONF', 'VALIDANDO_OBRA', 'EM_MEDICAO', 'EM_ADEQUACAO', 'ALINHANDO_CLIENTE', 'EM_AUDITORIA', 'AGUARD_ASSINATURA_TEC', 'EM_PRODUCAO', 'PRE_MONTAGEM', 'AGUARD_MERCADORIA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'EM_MONTAGEM', 'COM_OCORRENCIA', 'CHECKLIST_FINAL', 'POS_VENDA', 'EM_AT', 'RELACIONAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusprojeto'), nullable=True),
    sa.Column('status_alterado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_alterado_por', sa.Integer(), nullable=True),
    sa.Column('valor_contrato', sa.Float(), nullable=True),
    sa.Column('prazo_entrega_estimado', sa.Date(), nullable=True),
    sa.Column('ultima_movimentacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('alerta_parado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arquivado', sa.Boolean(), nullable=True),
    sa.Column('arquivado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arquivado_motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['conferente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projetista_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_alterado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_codigo'), 'projetos', ['codigo'], unique=True)
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    op.create_table('briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('cidade_obra', sa.String(length=100), nullable=True),
    sa.Column('estado_obra', sa.String(length=2), nullable=True),
    sa.Column('endereco_obra', sa.String(length=300), nullable=True),
    sa.Column('ambientes', sa.JSON(), nullable=True),
    sa.Column('prazo_desejado', sa.Date(), nullable=True),
    sa.Column('faixa_investimento_min', sa.Float(), nullable=True),
    sa.Column('faixa_investimento_max', sa.Float(), nullable=True),
    sa.Column('estilo_preferido', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('referencias_url', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_minimo', sa.Float(), nullable=True),
    sa.Column('score_detalhes', sa.JSON(), nullable=True),
    sa.Column('arquiteto_nome', sa.String(length=200), nullable=True),
    sa.Column('arquiteto_email', sa.String(length=200), nullable=True),
    sa.Column('arquiteto_telefone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aprovado_por_id', sa.Integer(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_devolucao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_index(op.f('ix_briefings_id'), 'briefings', ['id'], unique=False)
    op.create_table('fechamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('checklist_json', sa.JSON(), nullable=True),
    sa.Column('checklist_completo', sa.Boolean(), nullable=True),
    sa.Column('cadastro_aprovado', sa.Boolean(), nullable=True),
    sa.Column('cadastro_aprovado_por_id', sa.Integer(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_limite_assinatura', sa.Date(), nullable=True),
    sa.Column('contrato_assinado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contrato_url', sa.String(length=500), nullable=True),
    sa.Column('caderno_comercial_url', sa.String(length=500), nullable=True),
    sa.Column('onboarding_disparado', sa.Boolean(), nullable=True),
    sa.Column('onboarding_disparado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cadastro_aprovado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_index(op.f('ix_fechamentos_id'), 'fechamentos', ['id'], unique=False)
    op.create_table('fila_projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('projetista_id', sa.Integer(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('sla_dias', sa.Integer(), nullable=True),
    sa.Column('sla_vence_em', sa.Date(), nullable=True),
    sa.Column('sla_alerta_disparado', sa.Boolean(), nullable=True),
    sa.Column('data_entrada_fila', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_alocacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['projetista_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_index(op.f('ix_fila_projetos_id'), 'fila_projetos', ['id'], unique=False)
    op.create_table('handoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('checklist_json', sa.JSON(), nullable=True),
    sa.Column('checklist_completo', sa.Boolean(), nullable=True),
    sa.Column('liberado_por_id', sa.Integer(), nullable=True),
    sa.Column('liberado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['liberado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_index(op.f('ix_handoffs_id'), 'handoffs', ['id'], unique=False)
    op.create_table('historico_status_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('status_de', sa.Enum('NOVO_LEAD', 'QUALIFICANDO', 'EM_VISITA', 'EM_BRIEFING', 'NA_FILA', 'EM_PROJETO', 'AGUARD_VALIDACAO', 'EM_RENDER', 'AGUARD_APRESENTACAO', 'EM_AJUSTE', 'EM_FECHAMENTO', 'AGUARD_ASSINATURA', 'EM_HANDOFF', 'CONTATO_CONF', 'VALIDANDO_OBRA', 'EM_MEDICAO', 'EM_ADEQUACAO', 'ALINHANDO_CLIENTE', 'EM_AUDITORIA', 'AGUARD_ASSINATURA_TEC', 'EM_PRODUCAO', 'PRE_MONTAGEM', 'AGUARD_MERCADORIA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'EM_MONTAGEM', 'COM_OCORRENCIA', 'CHECKLIST_FINAL', 'POS_VENDA', 'EM_AT', 'RELACIONAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusprojeto'), nullable=True),
    sa.Column('status_para', sa.Enum('NOVO_LEAD', 'QUALIFICANDO', 'EM_VISITA', 'EM_BRIEFING', 'NA_FILA', 'EM_PROJETO', 'AGUARD_VALIDACAO', 'EM_RENDER', 'AGUARD_APRESENTACAO', 'EM_AJUSTE', 'EM_FECHAMENTO', 'AGUARD_ASSINATURA', 'EM_HANDOFF', 'CONTATO_CONF', 'VALIDANDO_OBRA', 'EM_MEDICAO', 'EM_ADEQUACAO', 'ALINHANDO_CLIENTE', 'EM_AUDITORIA', 'AGUARD_ASSINATURA_TEC', 'EM_PRODUCAO', 'PRE_MONTAGEM', 'AGUARD_MERCADORIA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'EM_MONTAGEM', 'COM_OCORRENCIA', 'CHECKLIST_FINAL', 'POS_VENDA', 'EM_AT', 'RELACIONAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusprojeto'), nullable=False),
    sa.Column('alterado_por_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alterado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_status_projeto_id'), 'historico_status_projeto', ['id'], unique=False)
    op.create_table('interacoes_arquitetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquiteto_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacoes_arquitetos_id'), 'interacoes_arquitetos', ['id'], unique=False)
    op.create_table('interacoes_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacoes_lead_id'), 'interacoes_lead', ['id'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('LEAD_SEM_INTERACAO', 'BRIEFING_SCORE_BAIXO', 'WIP_LIMIT_ATINGIDO', 'VERSAO_BASE_AGUARDANDO', 'EXCESSO_REAPRESENTACOES', 'CONTRATO_SEM_ASSINATURA', 'HANDOFF_BLOQUEADO', 'SLA_CONTATO_CONFERENTE', 'OBRA_REPROVADA', 'SLA_ADEQUACAO_VENCENDO', 'AUDITORIA_PENDENTE', 'NOVA_VERSAO_DOCUMENTO', 'PEDIDO_PARCIAL_PENDENTE', 'PRAZO_FABRICA_5_DIAS', 'PRAZO_FABRICA_VENCIDO', 'PRE_MONTAGEM_PENDENTE', 'OCORRENCIA_MONTAGEM', 'SLA_AT_VENCENDO', 'AT_CAUSA_REPETIDA', 'PROJETO_PARADO', 'ESPECIFICADOR_TRANSFERIDO', name='tiponotificacao'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('arquiteto_id', sa.Integer(), nullable=True),
    sa.Column('canal', sa.Enum('PUSH', 'EMAIL', 'TELA', 'WHATSAPP', name='canalnotificacao'), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('lida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_disparo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['destinatario_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.create_table('projetos_comerciais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=True),
    sa.Column('arquivo_url', sa.String(length=500), nullable=True),
    sa.Column('descricao_alteracao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submetido_para_validacao_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validado_por_id', sa.Integer(), nullable=True),
    sa.Column('validado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_devolucao', sa.Text(), nullable=True),
    sa.Column('numero_apresentacao', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['validado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_comerciais_id'), 'projetos_comerciais', ['id'], unique=False)
    op.create_table('ambientes_briefing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('briefing_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('COZINHA', 'CLOSET', 'DORMITORIO', 'SALA', 'BANHEIRO', 'LAVABO', 'HOME_OFFICE', 'GOURMET', 'AREA_SERVICO', 'OUTRO', name='tipoambiente'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('medidas_preliminares', sa.String(length=200), nullable=True),
    sa.Column('observacoes_especificas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['briefing_id'], ['briefings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambientes_briefing_id'), 'ambientes_briefing', ['id'], unique=False)
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechamento_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('comprovante_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['fechamento_id'], ['fechamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcelas_id'), 'parcelas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcelas_id'), table_name='parcelas')
    op.drop_table('parcelas')
    op.drop_index(op.f('ix_ambientes_briefing_id'), table_name='ambientes_briefing')
    op.drop_table('ambientes_briefing')
    op.drop_index(op.f('ix_projetos_comerciais_id'), table_name='projetos_comerciais')
    op.drop_table('projetos_comerciais')
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_interacoes_lead_id'), table_name='interacoes_lead')
    op.drop_table('interacoes_lead')
    op.drop_index(op.f('ix_interacoes_arquitetos_id'), table_name='interacoes_arquitetos')
    op.drop_table('interacoes_arquitetos')
    op.drop_index(op.f('ix_historico_status_projeto_id'), table_name='historico_status_projeto')
    op.drop_table('historico_status_projeto')
    op.drop_index(op.f('ix_handoffs_id'), table_name='handoffs')
    op.drop_table('handoffs')
    op.drop_index(op.f('ix_fila_projetos_id'), table_name='fila_projetos')
    op.drop_table('fila_projetos')
    op.drop_index(op.f('ix_fechamentos_id'), table_name='fechamentos')
    op.drop_table('fechamentos')
    op.drop_index(op.f('ix_briefings_id'), table_name='briefings')
    op.drop_table('briefings')
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_index(op.f('ix_projetos_codigo'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_historico_salarial_colaboradores_id'), table_name='historico_salarial_colaboradores')
    op.drop_table('historico_salarial_colaboradores')
    op.drop_index(op.f('ix_historico_cargo_colaboradores_id'), table_name='historico_cargo_colaboradores')
    op.drop_table('historico_cargo_colaboradores')
    op.drop_index(op.f('ix_documentos_colaboradores_id'), table_name='documentos_colaboradores')
    op.drop_table('documentos_colaboradores')
    op.drop_index(op.f('ix_historico_dono_arquitetos_id'), table_name='historico_dono_arquitetos')
    op.drop_table('historico_dono_arquitetos')
    op.drop_index(op.f('ix_decisores_arquitetos_id'), table_name='decisores_arquitetos')
    op.drop_table('decisores_arquitetos')
    op.drop_index(op.f('ix_concorrentes_arquitetos_id'), table_name='concorrentes_arquitetos')
    op.drop_table('concorrentes_arquitetos')
    op.drop_index(op.f('ix_colaboradores_id'), table_name='colaboradores')
    op.drop_index(op.f('ix_colaboradores_cpf'), table_name='colaboradores')
    op.drop_table('colaboradores')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_metas_visitas_consultor_id'), table_name='metas_visitas_consultor')
    op.drop_table('metas_visitas_consultor')
    op.drop_index(op.f('ix_config_wip_projetistas_id'), table_name='config_wip_projetistas')
    op.drop_table('config_wip_projetistas')
    op.drop_index(op.f('ix_cargos_id'), table_name='cargos')
    op.drop_table('cargos')
    op.drop_index(op.f('ix_arquitetos_id'), table_name='arquitetos')
    op.drop_table('arquitetos')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departamentos_id'), table_name='departamentos')
    op.drop_table('departamentos')
    # ### end Alembic commands ###