"""expande colaboradores e arquitetos - feature/arch

Revision ID: b9ac36585f2b
Revises: 94d29e691390
Create Date: 2026-07-28 23:43:09.967920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9ac36585f2b'
down_revision: Union[str, None] = '94d29e691390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios_arquiteto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquiteto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('funcao', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('decisor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_arquiteto_id'), 'funcionarios_arquiteto', ['id'], unique=False)
    op.create_table('interacoes_arquiteto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquiteto_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('VISITA_ESCRITORIO', 'LIGACAO', 'VISITA_LOJA', 'EVENTO', 'VIAGEM', 'ENVIO_BRINDE', name='tipointeracaoarquiteto'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacoes_arquiteto_id'), 'interacoes_arquiteto', ['id'], unique=False)
    op.drop_index('ix_departamentos_id', table_name='departamentos')
    op.drop_table('departamentos')
    op.drop_index('ix_documentos_colaboradores_id', table_name='documentos_colaboradores')
    op.drop_table('documentos_colaboradores')
    op.drop_index('ix_historico_dono_arquitetos_id', table_name='historico_dono_arquitetos')
    op.drop_table('historico_dono_arquitetos')
    op.drop_index('ix_metas_visitas_consultor_id', table_name='metas_visitas_consultor')
    op.drop_table('metas_visitas_consultor')
    op.drop_index('ix_cargos_id', table_name='cargos')
    op.drop_table('cargos')
    op.drop_index('ix_historico_cargo_colaboradores_id', table_name='historico_cargo_colaboradores')
    op.drop_table('historico_cargo_colaboradores')
    op.drop_index('ix_colaboradores_cpf', table_name='colaboradores')
    op.drop_index('ix_colaboradores_id', table_name='colaboradores')
    op.drop_table('colaboradores')
    op.drop_index('ix_historico_salarial_colaboradores_id', table_name='historico_salarial_colaboradores')
    op.drop_table('historico_salarial_colaboradores')
    op.drop_index('ix_interacoes_arquitetos_id', table_name='interacoes_arquitetos')
    op.drop_table('interacoes_arquitetos')
    op.add_column('arquitetos', sa.Column('vendedor_id', sa.Integer(), nullable=True))
    op.alter_column('arquitetos', 'tipo',
               existing_type=postgresql.ENUM('ARQUITETO', 'DESIGNER_INTERIORES', 'DECORADOR', 'ENGENHEIRO', 'CORRETOR', 'OUTRO', name='tipoespecificador'),
               type_=sa.Enum('ARQUITETO', 'ENGENHEIRO', 'DESIGNER', 'CORRETOR', 'OUTRO', name='tipoarquiteto'),
               nullable=True)
    op.drop_constraint('arquitetos_consultor_id_fkey', 'arquitetos', type_='foreignkey')
    op.create_foreign_key(None, 'arquitetos', 'users', ['vendedor_id'], ['id'])
    op.drop_column('arquitetos', 'especialidade')
    op.drop_column('arquitetos', 'status_carteira')
    op.drop_column('arquitetos', 'consultor_id')
    op.drop_constraint('notificacoes_arquiteto_id_fkey', 'notificacoes', type_='foreignkey')
    op.drop_column('notificacoes', 'arquiteto_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificacoes', sa.Column('arquiteto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('notificacoes_arquiteto_id_fkey', 'notificacoes', 'arquitetos', ['arquiteto_id'], ['id'])
    op.add_column('arquitetos', sa.Column('consultor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arquitetos', sa.Column('status_carteira', postgresql.ENUM('ATIVO', 'EM_PROSPECCAO', 'INATIVO', name='statuscarteiraespecificador'), autoincrement=False, nullable=False))
    op.add_column('arquitetos', sa.Column('especialidade', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'arquitetos', type_='foreignkey')
    op.create_foreign_key('arquitetos_consultor_id_fkey', 'arquitetos', 'users', ['consultor_id'], ['id'])
    op.alter_column('arquitetos', 'tipo',
               existing_type=sa.Enum('ARQUITETO', 'ENGENHEIRO', 'DESIGNER', 'CORRETOR', 'OUTRO', name='tipoarquiteto'),
               type_=postgresql.ENUM('ARQUITETO', 'DESIGNER_INTERIORES', 'DECORADOR', 'ENGENHEIRO', 'CORRETOR', 'OUTRO', name='tipoespecificador'),
               nullable=False)
    op.drop_column('arquitetos', 'vendedor_id')
    op.create_table('interacoes_arquitetos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('arquiteto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('responsavel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resumo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], name='interacoes_arquitetos_arquiteto_id_fkey'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='interacoes_arquitetos_lead_id_fkey'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], name='interacoes_arquitetos_responsavel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='interacoes_arquitetos_pkey')
    )
    op.create_index('ix_interacoes_arquitetos_id', 'interacoes_arquitetos', ['id'], unique=False)
    op.create_table('historico_salarial_colaboradores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('colaborador_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salario_clt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('remuneracao_complementar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('data_vigencia', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('registrado_por_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], name='historico_salarial_colaboradores_colaborador_id_fkey'),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], name='historico_salarial_colaboradores_registrado_por_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historico_salarial_colaboradores_pkey')
    )
    op.create_index('ix_historico_salarial_colaboradores_id', 'historico_salarial_colaboradores', ['id'], unique=False)
    op.create_table('colaboradores',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('colaboradores_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('rg', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('estado_civil', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('perfil_disc_primario', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('perfil_disc_secundario', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('observacoes_comportamentais', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('telefone_pessoal', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('telefone_corporativo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email_pessoal', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_corporativo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('endereco_logradouro', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('endereco_numero', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('endereco_complemento', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('endereco_bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('endereco_cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('endereco_estado', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('endereco_cep', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('data_admissao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('cargo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('departamento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('regime', postgresql.ENUM('CLT', 'PJ', name='regimecontratacao'), autoincrement=False, nullable=False),
    sa.Column('tipo_contrato', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pj_cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pj_contrato_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('pj_valor_mensal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pj_vigencia_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pj_vigencia_fim', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('salario_clt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('remuneracao_complementar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('data_vigencia_salario', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('carga_horaria', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('escala', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('modalidade', postgresql.ENUM('PRESENCIAL', 'HIBRIDO', 'REMOTO', name='modalidadetrabalho'), autoincrement=False, nullable=True),
    sa.Column('jornada_especial', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('banco', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('agencia', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('conta', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tipo_conta', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gestor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('data_desligamento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('tipo_desligamento', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('motivo_desligamento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entrevista_saida', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], name='colaboradores_cargo_id_fkey'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], name='colaboradores_departamento_id_fkey'),
    sa.ForeignKeyConstraint(['gestor_id'], ['colaboradores.id'], name='colaboradores_gestor_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='colaboradores_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='colaboradores_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_colaboradores_id', 'colaboradores', ['id'], unique=False)
    op.create_index('ix_colaboradores_cpf', 'colaboradores', ['cpf'], unique=True)
    op.create_table('historico_cargo_colaboradores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('colaborador_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cargo_anterior_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cargo_novo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('aprovado_por_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('justificativa', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['users.id'], name='historico_cargo_colaboradores_aprovado_por_id_fkey'),
    sa.ForeignKeyConstraint(['cargo_anterior_id'], ['cargos.id'], name='historico_cargo_colaboradores_cargo_anterior_id_fkey'),
    sa.ForeignKeyConstraint(['cargo_novo_id'], ['cargos.id'], name='historico_cargo_colaboradores_cargo_novo_id_fkey'),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], name='historico_cargo_colaboradores_colaborador_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historico_cargo_colaboradores_pkey')
    )
    op.create_index('ix_historico_cargo_colaboradores_id', 'historico_cargo_colaboradores', ['id'], unique=False)
    op.create_table('cargos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cargos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('departamento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], name='cargos_departamento_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cargos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_cargos_id', 'cargos', ['id'], unique=False)
    op.create_table('metas_visitas_consultor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('consultor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meta_visitas_mes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('configurado_por_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['configurado_por_id'], ['users.id'], name='metas_visitas_consultor_configurado_por_id_fkey'),
    sa.ForeignKeyConstraint(['consultor_id'], ['users.id'], name='metas_visitas_consultor_consultor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='metas_visitas_consultor_pkey'),
    sa.UniqueConstraint('consultor_id', name='metas_visitas_consultor_consultor_id_key')
    )
    op.create_index('ix_metas_visitas_consultor_id', 'metas_visitas_consultor', ['id'], unique=False)
    op.create_table('historico_dono_arquitetos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('arquiteto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consultor_anterior_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('consultor_novo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alterado_por_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alterado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alterado_por_id'], ['users.id'], name='historico_dono_arquitetos_alterado_por_id_fkey'),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], name='historico_dono_arquitetos_arquiteto_id_fkey'),
    sa.ForeignKeyConstraint(['consultor_anterior_id'], ['users.id'], name='historico_dono_arquitetos_consultor_anterior_id_fkey'),
    sa.ForeignKeyConstraint(['consultor_novo_id'], ['users.id'], name='historico_dono_arquitetos_consultor_novo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historico_dono_arquitetos_pkey')
    )
    op.create_index('ix_historico_dono_arquitetos_id', 'historico_dono_arquitetos', ['id'], unique=False)
    op.create_table('documentos_colaboradores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('colaborador_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('data_vencimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], name='documentos_colaboradores_colaborador_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='documentos_colaboradores_pkey')
    )
    op.create_index('ix_documentos_colaboradores_id', 'documentos_colaboradores', ['id'], unique=False)
    op.create_table('departamentos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='departamentos_pkey')
    )
    op.create_index('ix_departamentos_id', 'departamentos', ['id'], unique=False)
    op.drop_index(op.f('ix_interacoes_arquiteto_id'), table_name='interacoes_arquiteto')
    op.drop_table('interacoes_arquiteto')
    op.drop_index(op.f('ix_funcionarios_arquiteto_id'), table_name='funcionarios_arquiteto')
    op.drop_table('funcionarios_arquiteto')
    # ### end Alembic commands ###