"""baseline schema atual

Revision ID: f0d1e904df6f
Revises: 
Create Date: 2026-07-21 21:44:27.526299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d1e904df6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('perfil', sa.Enum('DIRETORIA', 'GERENTE_COMERCIAL', 'VENDEDOR', 'RECEPCAO', 'PROJETISTA', 'CONFERENTE', 'SUPERVISOR_MONTAGEM', 'GESTOR_LOGISTICA', 'SAC', 'FINANCEIRO', 'MONTADOR_PROPRIO', 'MONTADOR_TERCEIRO', 'ARQUITETO', 'CLIENTE', name='perfilusuario'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('arquitetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('ARQUITETO', 'ENGENHEIRO', 'DESIGNER', 'CORRETOR', 'OUTRO', name='tipoarquiteto'), nullable=True),
    sa.Column('escritorio', sa.String(length=200), nullable=True),
    sa.Column('endereco_escritorio', sa.String(length=300), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('nivel_parceria', sa.String(length=50), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_arquitetos_id'), 'arquitetos', ['id'], unique=False)
    op.create_table('config_wip_projetistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projetista_id', sa.Integer(), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['projetista_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projetista_id')
    )
    op.create_index(op.f('ix_config_wip_projetistas_id'), 'config_wip_projetistas', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('tipo', sa.Enum('PESSOA_FISICA', 'PESSOA_JURIDICA', name='tipocliente'), nullable=True),
    sa.Column('cadastro_aprovado', sa.Boolean(), nullable=True),
    sa.Column('cadastro_aprovado_por', sa.Integer(), nullable=True),
    sa.Column('cadastro_aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arquiteto_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['cadastro_aprovado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('concorrentes_arquitetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquiteto_id', sa.Integer(), nullable=False),
    sa.Column('nome_concorrente', sa.String(length=200), nullable=False),
    sa.Column('percentual_fechamento_estimado', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concorrentes_arquitetos_id'), 'concorrentes_arquitetos', ['id'], unique=False)
    op.create_table('decisores_arquitetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquiteto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('is_principal', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisores_arquitetos_id'), 'decisores_arquitetos', ['id'], unique=False)
    op.create_table('funcionarios_arquiteto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquiteto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('funcao', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('decisor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_arquiteto_id'), 'funcionarios_arquiteto', ['id'], unique=False)
    op.create_table('interacoes_arquiteto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquiteto_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('VISITA_ESCRITORIO', 'LIGACAO', 'VISITA_LOJA', 'EVENTO', 'VIAGEM', 'ENVIO_BRINDE', name='tipointeracaoarquiteto'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacoes_arquiteto_id'), 'interacoes_arquiteto', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('origem', sa.Enum('INSTAGRAM', 'INDICACAO', 'SITE_GOOGLE', 'CONSTRUTORA', 'SHOWROOM', 'ARQUITETO', 'OUTRO', name='origemlead'), nullable=False),
    sa.Column('campanha', sa.String(length=200), nullable=True),
    sa.Column('status_funil', sa.Enum('NOVO_LEAD', 'QUALIFICANDO', 'EM_VISITA', 'EM_BRIEFING', 'EM_PROJETO', 'EM_NEGOCIACAO', 'FECHADO', 'PERDIDO', 'DESQUALIFICADO', name='statusfunil'), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('arquiteto_id', sa.Integer(), nullable=True),
    sa.Column('qualificado', sa.Boolean(), nullable=True),
    sa.Column('motivo_perda', sa.Text(), nullable=True),
    sa.Column('concorrente_perdido', sa.String(length=200), nullable=True),
    sa.Column('convertido_em_cliente', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_interacao_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('projetista_id', sa.Integer(), nullable=True),
    sa.Column('conferente_id', sa.Integer(), nullable=True),
    sa.Column('arquiteto_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOVO_LEAD', 'QUALIFICANDO', 'EM_VISITA', 'EM_BRIEFING', 'NA_FILA', 'EM_PROJETO', 'AGUARD_VALIDACAO', 'EM_RENDER', 'AGUARD_APRESENTACAO', 'EM_AJUSTE', 'EM_FECHAMENTO', 'AGUARD_ASSINATURA', 'EM_HANDOFF', 'CONTATO_CONF', 'VALIDANDO_OBRA', 'EM_MEDICAO', 'EM_ADEQUACAO', 'ALINHANDO_CLIENTE', 'EM_AUDITORIA', 'AGUARD_ASSINATURA_TEC', 'EM_PRODUCAO', 'PRE_MONTAGEM', 'AGUARD_MERCADORIA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'EM_MONTAGEM', 'COM_OCORRENCIA', 'CHECKLIST_FINAL', 'POS_VENDA', 'EM_AT', 'RELACIONAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusprojeto'), nullable=True),
    sa.Column('status_anterior', sa.Enum('NOVO_LEAD', 'QUALIFICANDO', 'EM_VISITA', 'EM_BRIEFING', 'NA_FILA', 'EM_PROJETO', 'AGUARD_VALIDACAO', 'EM_RENDER', 'AGUARD_APRESENTACAO', 'EM_AJUSTE', 'EM_FECHAMENTO', 'AGUARD_ASSINATURA', 'EM_HANDOFF', 'CONTATO_CONF', 'VALIDANDO_OBRA', 'EM_MEDICAO', 'EM_ADEQUACAO', 'ALINHANDO_CLIENTE', 'EM_AUDITORIA', 'AGUARD_ASSINATURA_TEC', 'EM_PRODUCAO', 'PRE_MONTAGEM', 'AGUARD_MERCADORIA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'EM_MONTAGEM', 'COM_OCORRENCIA', 'CHECKLIST_FINAL', 'POS_VENDA', 'EM_AT', 'RELACIONAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusprojeto'), nullable=True),
    sa.Column('status_alterado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_alterado_por', sa.Integer(), nullable=True),
    sa.Column('valor_contrato', sa.Float(), nullable=True),
    sa.Column('prazo_entrega_estimado', sa.Date(), nullable=True),
    sa.Column('ultima_movimentacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('alerta_parado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arquivado', sa.Boolean(), nullable=True),
    sa.Column('arquivado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arquivado_motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['arquiteto_id'], ['arquitetos.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['conferente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projetista_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_alterado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_codigo'), 'projetos', ['codigo'], unique=True)
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    op.create_table('briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('cidade_obra', sa.String(length=100), nullable=True),
    sa.Column('estado_obra', sa.String(length=2), nullable=True),
    sa.Column('endereco_obra', sa.String(length=300), nullable=True),
    sa.Column('ambientes', sa.JSON(), nullable=True),
    sa.Column('prazo_desejado', sa.Date(), nullable=True),
    sa.Column('faixa_investimento_min', sa.Float(), nullable=True),
    sa.Column('faixa_investimento_max', sa.Float(), nullable=True),
    sa.Column('estilo_preferido', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('referencias_url', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_minimo', sa.Float(), nullable=True),
    sa.Column('score_detalhes', sa.JSON(), nullable=True),
    sa.Column('arquiteto_nome', sa.String(length=200), nullable=True),
    sa.Column('arquiteto_email', sa.String(length=200), nullable=True),
    sa.Column('arquiteto_telefone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aprovado_por_id', sa.Integer(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_devolucao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_index(op.f('ix_briefings_id'), 'briefings', ['id'], unique=False)
    op.create_table('fechamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('checklist_json', sa.JSON(), nullable=True),
    sa.Column('checklist_completo', sa.Boolean(), nullable=True),
    sa.Column('cadastro_aprovado', sa.Boolean(), nullable=True),
    sa.Column('cadastro_aprovado_por_id', sa.Integer(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_limite_assinatura', sa.Date(), nullable=True),
    sa.Column('contrato_assinado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contrato_url', sa.String(length=500), nullable=True),
    sa.Column('caderno_comercial_url', sa.String(length=500), nullable=True),
    sa.Column('onboarding_disparado', sa.Boolean(), nullable=True),
    sa.Column('onboarding_disparado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cadastro_aprovado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_index(op.f('ix_fechamentos_id'), 'fechamentos', ['id'], unique=False)
    op.create_table('fila_projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('projetista_id', sa.Integer(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('sla_dias', sa.Integer(), nullable=True),
    sa.Column('sla_vence_em', sa.Date(), nullable=True),
    sa.Column('sla_alerta_disparado', sa.Boolean(), nullable=True),
    sa.Column('data_entrada_fila', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_alocacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['projetista_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_index(op.f('ix_fila_projetos_id'), 'fila_projetos', ['id'], unique=False)
    op.create_table('handoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('checklist_json', sa.JSON(), nullable=True),
    sa.Column('checklist_completo', sa.Boolean(), nullable=True),
    sa.Column('liberado_por_id', sa.Integer(), nullable=True),
    sa.Column('liberado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['liberado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_index(op.f('ix_handoffs_id'), 'handoffs', ['id'], unique=False)
    op.create_table('historico_status_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('status_de', sa.Enum('NOVO_LEAD', 'QUALIFICANDO', 'EM_VISITA', 'EM_BRIEFING', 'NA_FILA', 'EM_PROJETO', 'AGUARD_VALIDACAO', 'EM_RENDER', 'AGUARD_APRESENTACAO', 'EM_AJUSTE', 'EM_FECHAMENTO', 'AGUARD_ASSINATURA', 'EM_HANDOFF', 'CONTATO_CONF', 'VALIDANDO_OBRA', 'EM_MEDICAO', 'EM_ADEQUACAO', 'ALINHANDO_CLIENTE', 'EM_AUDITORIA', 'AGUARD_ASSINATURA_TEC', 'EM_PRODUCAO', 'PRE_MONTAGEM', 'AGUARD_MERCADORIA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'EM_MONTAGEM', 'COM_OCORRENCIA', 'CHECKLIST_FINAL', 'POS_VENDA', 'EM_AT', 'RELACIONAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusprojeto'), nullable=True),
    sa.Column('status_para', sa.Enum('NOVO_LEAD', 'QUALIFICANDO', 'EM_VISITA', 'EM_BRIEFING', 'NA_FILA', 'EM_PROJETO', 'AGUARD_VALIDACAO', 'EM_RENDER', 'AGUARD_APRESENTACAO', 'EM_AJUSTE', 'EM_FECHAMENTO', 'AGUARD_ASSINATURA', 'EM_HANDOFF', 'CONTATO_CONF', 'VALIDANDO_OBRA', 'EM_MEDICAO', 'EM_ADEQUACAO', 'ALINHANDO_CLIENTE', 'EM_AUDITORIA', 'AGUARD_ASSINATURA_TEC', 'EM_PRODUCAO', 'PRE_MONTAGEM', 'AGUARD_MERCADORIA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'EM_MONTAGEM', 'COM_OCORRENCIA', 'CHECKLIST_FINAL', 'POS_VENDA', 'EM_AT', 'RELACIONAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusprojeto'), nullable=False),
    sa.Column('alterado_por_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alterado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_status_projeto_id'), 'historico_status_projeto', ['id'], unique=False)
    op.create_table('interacoes_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacoes_lead_id'), 'interacoes_lead', ['id'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('LEAD_SEM_INTERACAO', 'BRIEFING_SCORE_BAIXO', 'WIP_LIMIT_ATINGIDO', 'VERSAO_BASE_AGUARDANDO', 'EXCESSO_REAPRESENTACOES', 'CONTRATO_SEM_ASSINATURA', 'HANDOFF_BLOQUEADO', 'SLA_CONTATO_CONFERENTE', 'OBRA_REPROVADA', 'SLA_ADEQUACAO_VENCENDO', 'AUDITORIA_PENDENTE', 'NOVA_VERSAO_DOCUMENTO', 'PEDIDO_PARCIAL_PENDENTE', 'PRAZO_FABRICA_5_DIAS', 'PRAZO_FABRICA_VENCIDO', 'PRE_MONTAGEM_PENDENTE', 'OCORRENCIA_MONTAGEM', 'SLA_AT_VENCENDO', 'AT_CAUSA_REPETIDA', 'PROJETO_PARADO', name='tiponotificacao'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('canal', sa.Enum('PUSH', 'EMAIL', 'TELA', 'WHATSAPP', name='canalnotificacao'), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('lida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_disparo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.create_table('projetos_comerciais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=True),
    sa.Column('arquivo_url', sa.String(length=500), nullable=True),
    sa.Column('descricao_alteracao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submetido_para_validacao_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validado_por_id', sa.Integer(), nullable=True),
    sa.Column('validado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_devolucao', sa.Text(), nullable=True),
    sa.Column('numero_apresentacao', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['validado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_comerciais_id'), 'projetos_comerciais', ['id'], unique=False)
    op.create_table('ambientes_briefing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('briefing_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('COZINHA', 'CLOSET', 'DORMITORIO', 'SALA', 'BANHEIRO', 'LAVABO', 'HOME_OFFICE', 'GOURMET', 'AREA_SERVICO', 'OUTRO', name='tipoambiente'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('medidas_preliminares', sa.String(length=200), nullable=True),
    sa.Column('observacoes_especificas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['briefing_id'], ['briefings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambientes_briefing_id'), 'ambientes_briefing', ['id'], unique=False)
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechamento_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('comprovante_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['fechamento_id'], ['fechamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcelas_id'), 'parcelas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcelas_id'), table_name='parcelas')
    op.drop_table('parcelas')
    op.drop_index(op.f('ix_ambientes_briefing_id'), table_name='ambientes_briefing')
    op.drop_table('ambientes_briefing')
    op.drop_index(op.f('ix_projetos_comerciais_id'), table_name='projetos_comerciais')
    op.drop_table('projetos_comerciais')
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_interacoes_lead_id'), table_name='interacoes_lead')
    op.drop_table('interacoes_lead')
    op.drop_index(op.f('ix_historico_status_projeto_id'), table_name='historico_status_projeto')
    op.drop_table('historico_status_projeto')
    op.drop_index(op.f('ix_handoffs_id'), table_name='handoffs')
    op.drop_table('handoffs')
    op.drop_index(op.f('ix_fila_projetos_id'), table_name='fila_projetos')
    op.drop_table('fila_projetos')
    op.drop_index(op.f('ix_fechamentos_id'), table_name='fechamentos')
    op.drop_table('fechamentos')
    op.drop_index(op.f('ix_briefings_id'), table_name='briefings')
    op.drop_table('briefings')
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_index(op.f('ix_projetos_codigo'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_interacoes_arquiteto_id'), table_name='interacoes_arquiteto')
    op.drop_table('interacoes_arquiteto')
    op.drop_index(op.f('ix_funcionarios_arquiteto_id'), table_name='funcionarios_arquiteto')
    op.drop_table('funcionarios_arquiteto')
    op.drop_index(op.f('ix_decisores_arquitetos_id'), table_name='decisores_arquitetos')
    op.drop_table('decisores_arquitetos')
    op.drop_index(op.f('ix_concorrentes_arquitetos_id'), table_name='concorrentes_arquitetos')
    op.drop_table('concorrentes_arquitetos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_config_wip_projetistas_id'), table_name='config_wip_projetistas')
    op.drop_table('config_wip_projetistas')
    op.drop_index(op.f('ix_arquitetos_id'), table_name='arquitetos')
    op.drop_table('arquitetos')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
