/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'session.create': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.create']['types'],
  },
  'session.store': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.store']['types'],
  },
  'dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard']['types'],
  },
  'session.destroy': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['session.destroy']['types'],
  },
  'crm.index': {
    methods: ["GET","HEAD"],
    pattern: '/crm',
    tokens: [{"old":"/crm","type":0,"val":"crm","end":""}],
    types: placeholder as Registry['crm.index']['types'],
  },
  'crm.leads.store': {
    methods: ["POST"],
    pattern: '/crm/leads',
    tokens: [{"old":"/crm/leads","type":0,"val":"crm","end":""},{"old":"/crm/leads","type":0,"val":"leads","end":""}],
    types: placeholder as Registry['crm.leads.store']['types'],
  },
  'crm.leads.update_status': {
    methods: ["PATCH"],
    pattern: '/crm/leads/:id/status',
    tokens: [{"old":"/crm/leads/:id/status","type":0,"val":"crm","end":""},{"old":"/crm/leads/:id/status","type":0,"val":"leads","end":""},{"old":"/crm/leads/:id/status","type":1,"val":"id","end":""},{"old":"/crm/leads/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['crm.leads.update_status']['types'],
  },
  'crm.leads.qualificar': {
    methods: ["POST"],
    pattern: '/crm/leads/:id/qualificar',
    tokens: [{"old":"/crm/leads/:id/qualificar","type":0,"val":"crm","end":""},{"old":"/crm/leads/:id/qualificar","type":0,"val":"leads","end":""},{"old":"/crm/leads/:id/qualificar","type":1,"val":"id","end":""},{"old":"/crm/leads/:id/qualificar","type":0,"val":"qualificar","end":""}],
    types: placeholder as Registry['crm.leads.qualificar']['types'],
  },
  'crm.leads.desqualificar': {
    methods: ["POST"],
    pattern: '/crm/leads/:id/desqualificar',
    tokens: [{"old":"/crm/leads/:id/desqualificar","type":0,"val":"crm","end":""},{"old":"/crm/leads/:id/desqualificar","type":0,"val":"leads","end":""},{"old":"/crm/leads/:id/desqualificar","type":1,"val":"id","end":""},{"old":"/crm/leads/:id/desqualificar","type":0,"val":"desqualificar","end":""}],
    types: placeholder as Registry['crm.leads.desqualificar']['types'],
  },
  'crm.leads.marcar_perdido': {
    methods: ["POST"],
    pattern: '/crm/leads/:id/perder',
    tokens: [{"old":"/crm/leads/:id/perder","type":0,"val":"crm","end":""},{"old":"/crm/leads/:id/perder","type":0,"val":"leads","end":""},{"old":"/crm/leads/:id/perder","type":1,"val":"id","end":""},{"old":"/crm/leads/:id/perder","type":0,"val":"perder","end":""}],
    types: placeholder as Registry['crm.leads.marcar_perdido']['types'],
  },
  'crm.leads.registrar_interacao': {
    methods: ["POST"],
    pattern: '/crm/leads/:id/interacoes',
    tokens: [{"old":"/crm/leads/:id/interacoes","type":0,"val":"crm","end":""},{"old":"/crm/leads/:id/interacoes","type":0,"val":"leads","end":""},{"old":"/crm/leads/:id/interacoes","type":1,"val":"id","end":""},{"old":"/crm/leads/:id/interacoes","type":0,"val":"interacoes","end":""}],
    types: placeholder as Registry['crm.leads.registrar_interacao']['types'],
  },
  'briefings.index': {
    methods: ["GET","HEAD"],
    pattern: '/briefings',
    tokens: [{"old":"/briefings","type":0,"val":"briefings","end":""}],
    types: placeholder as Registry['briefings.index']['types'],
  },
  'briefings.store': {
    methods: ["POST"],
    pattern: '/briefings',
    tokens: [{"old":"/briefings","type":0,"val":"briefings","end":""}],
    types: placeholder as Registry['briefings.store']['types'],
  },
  'briefings.calcular_score': {
    methods: ["POST"],
    pattern: '/briefings/calcular-score',
    tokens: [{"old":"/briefings/calcular-score","type":0,"val":"briefings","end":""},{"old":"/briefings/calcular-score","type":0,"val":"calcular-score","end":""}],
    types: placeholder as Registry['briefings.calcular_score']['types'],
  },
  'briefings.edit': {
    methods: ["GET","HEAD"],
    pattern: '/briefings/:id/edit',
    tokens: [{"old":"/briefings/:id/edit","type":0,"val":"briefings","end":""},{"old":"/briefings/:id/edit","type":1,"val":"id","end":""},{"old":"/briefings/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['briefings.edit']['types'],
  },
  'briefings.update': {
    methods: ["PUT"],
    pattern: '/briefings/:id',
    tokens: [{"old":"/briefings/:id","type":0,"val":"briefings","end":""},{"old":"/briefings/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['briefings.update']['types'],
  },
  'briefings.enviar_para_fila': {
    methods: ["POST"],
    pattern: '/briefings/:id/enviar-para-fila',
    tokens: [{"old":"/briefings/:id/enviar-para-fila","type":0,"val":"briefings","end":""},{"old":"/briefings/:id/enviar-para-fila","type":1,"val":"id","end":""},{"old":"/briefings/:id/enviar-para-fila","type":0,"val":"enviar-para-fila","end":""}],
    types: placeholder as Registry['briefings.enviar_para_fila']['types'],
  },
  'fila.index': {
    methods: ["GET","HEAD"],
    pattern: '/fila',
    tokens: [{"old":"/fila","type":0,"val":"fila","end":""}],
    types: placeholder as Registry['fila.index']['types'],
  },
  'wip.configurar': {
    methods: ["POST"],
    pattern: '/wip/configuracoes',
    tokens: [{"old":"/wip/configuracoes","type":0,"val":"wip","end":""},{"old":"/wip/configuracoes","type":0,"val":"configuracoes","end":""}],
    types: placeholder as Registry['wip.configurar']['types'],
  },
  'fila.alocar': {
    methods: ["POST"],
    pattern: '/fila/:id/alocar',
    tokens: [{"old":"/fila/:id/alocar","type":0,"val":"fila","end":""},{"old":"/fila/:id/alocar","type":1,"val":"id","end":""},{"old":"/fila/:id/alocar","type":0,"val":"alocar","end":""}],
    types: placeholder as Registry['fila.alocar']['types'],
  },
  'fila.desalocar': {
    methods: ["POST"],
    pattern: '/fila/:id/desalocar',
    tokens: [{"old":"/fila/:id/desalocar","type":0,"val":"fila","end":""},{"old":"/fila/:id/desalocar","type":1,"val":"id","end":""},{"old":"/fila/:id/desalocar","type":0,"val":"desalocar","end":""}],
    types: placeholder as Registry['fila.desalocar']['types'],
  },
  'fila.iniciar': {
    methods: ["POST"],
    pattern: '/fila/:id/iniciar',
    tokens: [{"old":"/fila/:id/iniciar","type":0,"val":"fila","end":""},{"old":"/fila/:id/iniciar","type":1,"val":"id","end":""},{"old":"/fila/:id/iniciar","type":0,"val":"iniciar","end":""}],
    types: placeholder as Registry['fila.iniciar']['types'],
  },
  'especificadores.index': {
    methods: ["GET","HEAD"],
    pattern: '/especificadores',
    tokens: [{"old":"/especificadores","type":0,"val":"especificadores","end":""}],
    types: placeholder as Registry['especificadores.index']['types'],
  },
  'especificadores.store': {
    methods: ["POST"],
    pattern: '/especificadores',
    tokens: [{"old":"/especificadores","type":0,"val":"especificadores","end":""}],
    types: placeholder as Registry['especificadores.store']['types'],
  },
  'especificadores.kpis': {
    methods: ["GET","HEAD"],
    pattern: '/especificadores/kpis',
    tokens: [{"old":"/especificadores/kpis","type":0,"val":"especificadores","end":""},{"old":"/especificadores/kpis","type":0,"val":"kpis","end":""}],
    types: placeholder as Registry['especificadores.kpis']['types'],
  },
  'especificadores.metas.index': {
    methods: ["GET","HEAD"],
    pattern: '/especificadores/metas-visitas',
    tokens: [{"old":"/especificadores/metas-visitas","type":0,"val":"especificadores","end":""},{"old":"/especificadores/metas-visitas","type":0,"val":"metas-visitas","end":""}],
    types: placeholder as Registry['especificadores.metas.index']['types'],
  },
  'especificadores.metas.update': {
    methods: ["PUT"],
    pattern: '/especificadores/metas-visitas',
    tokens: [{"old":"/especificadores/metas-visitas","type":0,"val":"especificadores","end":""},{"old":"/especificadores/metas-visitas","type":0,"val":"metas-visitas","end":""}],
    types: placeholder as Registry['especificadores.metas.update']['types'],
  },
  'especificadores.metas.me': {
    methods: ["GET","HEAD"],
    pattern: '/especificadores/metas-visitas/me',
    tokens: [{"old":"/especificadores/metas-visitas/me","type":0,"val":"especificadores","end":""},{"old":"/especificadores/metas-visitas/me","type":0,"val":"metas-visitas","end":""},{"old":"/especificadores/metas-visitas/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['especificadores.metas.me']['types'],
  },
  'especificadores.show': {
    methods: ["GET","HEAD"],
    pattern: '/especificadores/:id',
    tokens: [{"old":"/especificadores/:id","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['especificadores.show']['types'],
  },
  'especificadores.update': {
    methods: ["PATCH"],
    pattern: '/especificadores/:id',
    tokens: [{"old":"/especificadores/:id","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['especificadores.update']['types'],
  },
  'especificadores.destroy': {
    methods: ["DELETE"],
    pattern: '/especificadores/:id',
    tokens: [{"old":"/especificadores/:id","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['especificadores.destroy']['types'],
  },
  'especificadores.reatribuir_dono': {
    methods: ["PATCH"],
    pattern: '/especificadores/:id/dono',
    tokens: [{"old":"/especificadores/:id/dono","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/dono","type":1,"val":"id","end":""},{"old":"/especificadores/:id/dono","type":0,"val":"dono","end":""}],
    types: placeholder as Registry['especificadores.reatribuir_dono']['types'],
  },
  'especificadores.historico_dono': {
    methods: ["GET","HEAD"],
    pattern: '/especificadores/:id/historico-dono',
    tokens: [{"old":"/especificadores/:id/historico-dono","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/historico-dono","type":1,"val":"id","end":""},{"old":"/especificadores/:id/historico-dono","type":0,"val":"historico-dono","end":""}],
    types: placeholder as Registry['especificadores.historico_dono']['types'],
  },
  'especificadores.score': {
    methods: ["GET","HEAD"],
    pattern: '/especificadores/:id/score',
    tokens: [{"old":"/especificadores/:id/score","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/score","type":1,"val":"id","end":""},{"old":"/especificadores/:id/score","type":0,"val":"score","end":""}],
    types: placeholder as Registry['especificadores.score']['types'],
  },
  'especificadores.decisores.index': {
    methods: ["GET","HEAD"],
    pattern: '/especificadores/:id/decisores',
    tokens: [{"old":"/especificadores/:id/decisores","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/decisores","type":1,"val":"id","end":""},{"old":"/especificadores/:id/decisores","type":0,"val":"decisores","end":""}],
    types: placeholder as Registry['especificadores.decisores.index']['types'],
  },
  'especificadores.decisores.store': {
    methods: ["POST"],
    pattern: '/especificadores/:id/decisores',
    tokens: [{"old":"/especificadores/:id/decisores","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/decisores","type":1,"val":"id","end":""},{"old":"/especificadores/:id/decisores","type":0,"val":"decisores","end":""}],
    types: placeholder as Registry['especificadores.decisores.store']['types'],
  },
  'especificadores.decisores.update': {
    methods: ["PATCH"],
    pattern: '/especificadores/:id/decisores/:decisorId',
    tokens: [{"old":"/especificadores/:id/decisores/:decisorId","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/decisores/:decisorId","type":1,"val":"id","end":""},{"old":"/especificadores/:id/decisores/:decisorId","type":0,"val":"decisores","end":""},{"old":"/especificadores/:id/decisores/:decisorId","type":1,"val":"decisorId","end":""}],
    types: placeholder as Registry['especificadores.decisores.update']['types'],
  },
  'especificadores.decisores.destroy': {
    methods: ["DELETE"],
    pattern: '/especificadores/:id/decisores/:decisorId',
    tokens: [{"old":"/especificadores/:id/decisores/:decisorId","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/decisores/:decisorId","type":1,"val":"id","end":""},{"old":"/especificadores/:id/decisores/:decisorId","type":0,"val":"decisores","end":""},{"old":"/especificadores/:id/decisores/:decisorId","type":1,"val":"decisorId","end":""}],
    types: placeholder as Registry['especificadores.decisores.destroy']['types'],
  },
  'especificadores.concorrentes.index': {
    methods: ["GET","HEAD"],
    pattern: '/especificadores/:id/concorrentes',
    tokens: [{"old":"/especificadores/:id/concorrentes","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/concorrentes","type":1,"val":"id","end":""},{"old":"/especificadores/:id/concorrentes","type":0,"val":"concorrentes","end":""}],
    types: placeholder as Registry['especificadores.concorrentes.index']['types'],
  },
  'especificadores.concorrentes.store': {
    methods: ["POST"],
    pattern: '/especificadores/:id/concorrentes',
    tokens: [{"old":"/especificadores/:id/concorrentes","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/concorrentes","type":1,"val":"id","end":""},{"old":"/especificadores/:id/concorrentes","type":0,"val":"concorrentes","end":""}],
    types: placeholder as Registry['especificadores.concorrentes.store']['types'],
  },
  'especificadores.concorrentes.update': {
    methods: ["PATCH"],
    pattern: '/especificadores/:id/concorrentes/:concorrenteId',
    tokens: [{"old":"/especificadores/:id/concorrentes/:concorrenteId","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/concorrentes/:concorrenteId","type":1,"val":"id","end":""},{"old":"/especificadores/:id/concorrentes/:concorrenteId","type":0,"val":"concorrentes","end":""},{"old":"/especificadores/:id/concorrentes/:concorrenteId","type":1,"val":"concorrenteId","end":""}],
    types: placeholder as Registry['especificadores.concorrentes.update']['types'],
  },
  'especificadores.concorrentes.destroy': {
    methods: ["DELETE"],
    pattern: '/especificadores/:id/concorrentes/:concorrenteId',
    tokens: [{"old":"/especificadores/:id/concorrentes/:concorrenteId","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/concorrentes/:concorrenteId","type":1,"val":"id","end":""},{"old":"/especificadores/:id/concorrentes/:concorrenteId","type":0,"val":"concorrentes","end":""},{"old":"/especificadores/:id/concorrentes/:concorrenteId","type":1,"val":"concorrenteId","end":""}],
    types: placeholder as Registry['especificadores.concorrentes.destroy']['types'],
  },
  'especificadores.interacoes.index': {
    methods: ["GET","HEAD"],
    pattern: '/especificadores/:id/interacoes',
    tokens: [{"old":"/especificadores/:id/interacoes","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/interacoes","type":1,"val":"id","end":""},{"old":"/especificadores/:id/interacoes","type":0,"val":"interacoes","end":""}],
    types: placeholder as Registry['especificadores.interacoes.index']['types'],
  },
  'especificadores.interacoes.store': {
    methods: ["POST"],
    pattern: '/especificadores/:id/interacoes',
    tokens: [{"old":"/especificadores/:id/interacoes","type":0,"val":"especificadores","end":""},{"old":"/especificadores/:id/interacoes","type":1,"val":"id","end":""},{"old":"/especificadores/:id/interacoes","type":0,"val":"interacoes","end":""}],
    types: placeholder as Registry['especificadores.interacoes.store']['types'],
  },
  'colaboradores.departamentos.index': {
    methods: ["GET","HEAD"],
    pattern: '/colaboradores/departamentos',
    tokens: [{"old":"/colaboradores/departamentos","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/departamentos","type":0,"val":"departamentos","end":""}],
    types: placeholder as Registry['colaboradores.departamentos.index']['types'],
  },
  'colaboradores.departamentos.store': {
    methods: ["POST"],
    pattern: '/colaboradores/departamentos',
    tokens: [{"old":"/colaboradores/departamentos","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/departamentos","type":0,"val":"departamentos","end":""}],
    types: placeholder as Registry['colaboradores.departamentos.store']['types'],
  },
  'colaboradores.departamentos.update': {
    methods: ["PUT"],
    pattern: '/colaboradores/departamentos/:id',
    tokens: [{"old":"/colaboradores/departamentos/:id","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/departamentos/:id","type":0,"val":"departamentos","end":""},{"old":"/colaboradores/departamentos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['colaboradores.departamentos.update']['types'],
  },
  'colaboradores.cargos.index': {
    methods: ["GET","HEAD"],
    pattern: '/colaboradores/cargos',
    tokens: [{"old":"/colaboradores/cargos","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/cargos","type":0,"val":"cargos","end":""}],
    types: placeholder as Registry['colaboradores.cargos.index']['types'],
  },
  'colaboradores.cargos.store': {
    methods: ["POST"],
    pattern: '/colaboradores/cargos',
    tokens: [{"old":"/colaboradores/cargos","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/cargos","type":0,"val":"cargos","end":""}],
    types: placeholder as Registry['colaboradores.cargos.store']['types'],
  },
  'colaboradores.cargos.update': {
    methods: ["PUT"],
    pattern: '/colaboradores/cargos/:id',
    tokens: [{"old":"/colaboradores/cargos/:id","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/cargos/:id","type":0,"val":"cargos","end":""},{"old":"/colaboradores/cargos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['colaboradores.cargos.update']['types'],
  },
  'colaboradores.index': {
    methods: ["GET","HEAD"],
    pattern: '/colaboradores',
    tokens: [{"old":"/colaboradores","type":0,"val":"colaboradores","end":""}],
    types: placeholder as Registry['colaboradores.index']['types'],
  },
  'colaboradores.store': {
    methods: ["POST"],
    pattern: '/colaboradores',
    tokens: [{"old":"/colaboradores","type":0,"val":"colaboradores","end":""}],
    types: placeholder as Registry['colaboradores.store']['types'],
  },
  'colaboradores.show': {
    methods: ["GET","HEAD"],
    pattern: '/colaboradores/:id',
    tokens: [{"old":"/colaboradores/:id","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['colaboradores.show']['types'],
  },
  'colaboradores.update': {
    methods: ["PUT"],
    pattern: '/colaboradores/:id',
    tokens: [{"old":"/colaboradores/:id","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['colaboradores.update']['types'],
  },
  'colaboradores.patch': {
    methods: ["PATCH"],
    pattern: '/colaboradores/:id',
    tokens: [{"old":"/colaboradores/:id","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['colaboradores.patch']['types'],
  },
  'colaboradores.destroy': {
    methods: ["DELETE"],
    pattern: '/colaboradores/:id',
    tokens: [{"old":"/colaboradores/:id","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['colaboradores.destroy']['types'],
  },
  'colaboradores.historico_salarial.store': {
    methods: ["POST"],
    pattern: '/colaboradores/:id/historico-salarial',
    tokens: [{"old":"/colaboradores/:id/historico-salarial","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/:id/historico-salarial","type":1,"val":"id","end":""},{"old":"/colaboradores/:id/historico-salarial","type":0,"val":"historico-salarial","end":""}],
    types: placeholder as Registry['colaboradores.historico_salarial.store']['types'],
  },
  'colaboradores.historico_cargo.store': {
    methods: ["POST"],
    pattern: '/colaboradores/:id/historico-cargo',
    tokens: [{"old":"/colaboradores/:id/historico-cargo","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/:id/historico-cargo","type":1,"val":"id","end":""},{"old":"/colaboradores/:id/historico-cargo","type":0,"val":"historico-cargo","end":""}],
    types: placeholder as Registry['colaboradores.historico_cargo.store']['types'],
  },
  'colaboradores.desligar': {
    methods: ["POST"],
    pattern: '/colaboradores/:id/desligar',
    tokens: [{"old":"/colaboradores/:id/desligar","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/:id/desligar","type":1,"val":"id","end":""},{"old":"/colaboradores/:id/desligar","type":0,"val":"desligar","end":""}],
    types: placeholder as Registry['colaboradores.desligar']['types'],
  },
  'colaboradores.documentos.store': {
    methods: ["POST"],
    pattern: '/colaboradores/:id/documentos',
    tokens: [{"old":"/colaboradores/:id/documentos","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/:id/documentos","type":1,"val":"id","end":""},{"old":"/colaboradores/:id/documentos","type":0,"val":"documentos","end":""}],
    types: placeholder as Registry['colaboradores.documentos.store']['types'],
  },
  'colaboradores.documentos.destroy': {
    methods: ["DELETE"],
    pattern: '/colaboradores/:id/documentos/:documentoId',
    tokens: [{"old":"/colaboradores/:id/documentos/:documentoId","type":0,"val":"colaboradores","end":""},{"old":"/colaboradores/:id/documentos/:documentoId","type":1,"val":"id","end":""},{"old":"/colaboradores/:id/documentos/:documentoId","type":0,"val":"documentos","end":""},{"old":"/colaboradores/:id/documentos/:documentoId","type":1,"val":"documentoId","end":""}],
    types: placeholder as Registry['colaboradores.documentos.destroy']['types'],
  },
  'clientes.index': {
    methods: ["GET","HEAD"],
    pattern: '/clientes',
    tokens: [{"old":"/clientes","type":0,"val":"clientes","end":""}],
    types: placeholder as Registry['clientes.index']['types'],
  },
  'clientes.store': {
    methods: ["POST"],
    pattern: '/clientes',
    tokens: [{"old":"/clientes","type":0,"val":"clientes","end":""}],
    types: placeholder as Registry['clientes.store']['types'],
  },
  'clientes.show': {
    methods: ["GET","HEAD"],
    pattern: '/clientes/:id',
    tokens: [{"old":"/clientes/:id","type":0,"val":"clientes","end":""},{"old":"/clientes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['clientes.show']['types'],
  },
  'clientes.update': {
    methods: ["PUT"],
    pattern: '/clientes/:id',
    tokens: [{"old":"/clientes/:id","type":0,"val":"clientes","end":""},{"old":"/clientes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['clientes.update']['types'],
  },
  'clientes.patch': {
    methods: ["PATCH"],
    pattern: '/clientes/:id',
    tokens: [{"old":"/clientes/:id","type":0,"val":"clientes","end":""},{"old":"/clientes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['clientes.patch']['types'],
  },
  'clientes.aprovar': {
    methods: ["POST"],
    pattern: '/clientes/:id/aprovar',
    tokens: [{"old":"/clientes/:id/aprovar","type":0,"val":"clientes","end":""},{"old":"/clientes/:id/aprovar","type":1,"val":"id","end":""},{"old":"/clientes/:id/aprovar","type":0,"val":"aprovar","end":""}],
    types: placeholder as Registry['clientes.aprovar']['types'],
  },
  'clientes.enderecos.store': {
    methods: ["POST"],
    pattern: '/clientes/:id/enderecos',
    tokens: [{"old":"/clientes/:id/enderecos","type":0,"val":"clientes","end":""},{"old":"/clientes/:id/enderecos","type":1,"val":"id","end":""},{"old":"/clientes/:id/enderecos","type":0,"val":"enderecos","end":""}],
    types: placeholder as Registry['clientes.enderecos.store']['types'],
  },
  'clientes.enderecos.destroy': {
    methods: ["DELETE"],
    pattern: '/clientes/:id/enderecos/:enderecoId',
    tokens: [{"old":"/clientes/:id/enderecos/:enderecoId","type":0,"val":"clientes","end":""},{"old":"/clientes/:id/enderecos/:enderecoId","type":1,"val":"id","end":""},{"old":"/clientes/:id/enderecos/:enderecoId","type":0,"val":"enderecos","end":""},{"old":"/clientes/:id/enderecos/:enderecoId","type":1,"val":"enderecoId","end":""}],
    types: placeholder as Registry['clientes.enderecos.destroy']['types'],
  },
  'clientes.converter_lead': {
    methods: ["POST"],
    pattern: '/clientes/converter-lead/:leadId',
    tokens: [{"old":"/clientes/converter-lead/:leadId","type":0,"val":"clientes","end":""},{"old":"/clientes/converter-lead/:leadId","type":0,"val":"converter-lead","end":""},{"old":"/clientes/converter-lead/:leadId","type":1,"val":"leadId","end":""}],
    types: placeholder as Registry['clientes.converter_lead']['types'],
  },
  'projetos.index': {
    methods: ["GET","HEAD"],
    pattern: '/projetos',
    tokens: [{"old":"/projetos","type":0,"val":"projetos","end":""}],
    types: placeholder as Registry['projetos.index']['types'],
  },
  'projetos.show': {
    methods: ["GET","HEAD"],
    pattern: '/projetos/:id',
    tokens: [{"old":"/projetos/:id","type":0,"val":"projetos","end":""},{"old":"/projetos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['projetos.show']['types'],
  },
  'projetos.mudar_status': {
    methods: ["POST"],
    pattern: '/projetos/:id/status',
    tokens: [{"old":"/projetos/:id/status","type":0,"val":"projetos","end":""},{"old":"/projetos/:id/status","type":1,"val":"id","end":""},{"old":"/projetos/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['projetos.mudar_status']['types'],
  },
  'projetos.arquivar': {
    methods: ["POST"],
    pattern: '/projetos/:id/arquivar',
    tokens: [{"old":"/projetos/:id/arquivar","type":0,"val":"projetos","end":""},{"old":"/projetos/:id/arquivar","type":1,"val":"id","end":""},{"old":"/projetos/:id/arquivar","type":0,"val":"arquivar","end":""}],
    types: placeholder as Registry['projetos.arquivar']['types'],
  },
  'projetos.versoes_3d.store': {
    methods: ["POST"],
    pattern: '/projetos/:id/versoes-3d',
    tokens: [{"old":"/projetos/:id/versoes-3d","type":0,"val":"projetos","end":""},{"old":"/projetos/:id/versoes-3d","type":1,"val":"id","end":""},{"old":"/projetos/:id/versoes-3d","type":0,"val":"versoes-3d","end":""}],
    types: placeholder as Registry['projetos.versoes_3d.store']['types'],
  },
  'projetos.versoes_3d.avaliar': {
    methods: ["POST"],
    pattern: '/projetos/:id/versoes-3d/:versaoId/avaliar',
    tokens: [{"old":"/projetos/:id/versoes-3d/:versaoId/avaliar","type":0,"val":"projetos","end":""},{"old":"/projetos/:id/versoes-3d/:versaoId/avaliar","type":1,"val":"id","end":""},{"old":"/projetos/:id/versoes-3d/:versaoId/avaliar","type":0,"val":"versoes-3d","end":""},{"old":"/projetos/:id/versoes-3d/:versaoId/avaliar","type":1,"val":"versaoId","end":""},{"old":"/projetos/:id/versoes-3d/:versaoId/avaliar","type":0,"val":"avaliar","end":""}],
    types: placeholder as Registry['projetos.versoes_3d.avaliar']['types'],
  },
  'projetos.versoes_3d.concluir_render': {
    methods: ["POST"],
    pattern: '/projetos/:id/versoes-3d/:versaoId/concluir-render',
    tokens: [{"old":"/projetos/:id/versoes-3d/:versaoId/concluir-render","type":0,"val":"projetos","end":""},{"old":"/projetos/:id/versoes-3d/:versaoId/concluir-render","type":1,"val":"id","end":""},{"old":"/projetos/:id/versoes-3d/:versaoId/concluir-render","type":0,"val":"versoes-3d","end":""},{"old":"/projetos/:id/versoes-3d/:versaoId/concluir-render","type":1,"val":"versaoId","end":""},{"old":"/projetos/:id/versoes-3d/:versaoId/concluir-render","type":0,"val":"concluir-render","end":""}],
    types: placeholder as Registry['projetos.versoes_3d.concluir_render']['types'],
  },
  'projetos.fechamento.show': {
    methods: ["GET","HEAD"],
    pattern: '/projetos/:id/fechamento',
    tokens: [{"old":"/projetos/:id/fechamento","type":0,"val":"projetos","end":""},{"old":"/projetos/:id/fechamento","type":1,"val":"id","end":""},{"old":"/projetos/:id/fechamento","type":0,"val":"fechamento","end":""}],
    types: placeholder as Registry['projetos.fechamento.show']['types'],
  },
  'projetos.fechamento.store': {
    methods: ["POST"],
    pattern: '/projetos/:id/fechamento',
    tokens: [{"old":"/projetos/:id/fechamento","type":0,"val":"projetos","end":""},{"old":"/projetos/:id/fechamento","type":1,"val":"id","end":""},{"old":"/projetos/:id/fechamento","type":0,"val":"fechamento","end":""}],
    types: placeholder as Registry['projetos.fechamento.store']['types'],
  },
  'projetos.fechamento.parcelas.pagar': {
    methods: ["POST"],
    pattern: '/projetos/:id/fechamento/parcelas/:parcelaId/pagar',
    tokens: [{"old":"/projetos/:id/fechamento/parcelas/:parcelaId/pagar","type":0,"val":"projetos","end":""},{"old":"/projetos/:id/fechamento/parcelas/:parcelaId/pagar","type":1,"val":"id","end":""},{"old":"/projetos/:id/fechamento/parcelas/:parcelaId/pagar","type":0,"val":"fechamento","end":""},{"old":"/projetos/:id/fechamento/parcelas/:parcelaId/pagar","type":0,"val":"parcelas","end":""},{"old":"/projetos/:id/fechamento/parcelas/:parcelaId/pagar","type":1,"val":"parcelaId","end":""},{"old":"/projetos/:id/fechamento/parcelas/:parcelaId/pagar","type":0,"val":"pagar","end":""}],
    types: placeholder as Registry['projetos.fechamento.parcelas.pagar']['types'],
  },
  'projetos.handoff.store': {
    methods: ["POST"],
    pattern: '/projetos/:id/handoff',
    tokens: [{"old":"/projetos/:id/handoff","type":0,"val":"projetos","end":""},{"old":"/projetos/:id/handoff","type":1,"val":"id","end":""},{"old":"/projetos/:id/handoff","type":0,"val":"handoff","end":""}],
    types: placeholder as Registry['projetos.handoff.store']['types'],
  },
  'configuracoes.index': {
    methods: ["GET","HEAD"],
    pattern: '/configuracoes',
    tokens: [{"old":"/configuracoes","type":0,"val":"configuracoes","end":""}],
    types: placeholder as Registry['configuracoes.index']['types'],
  },
  'configuracoes.ambientes.store': {
    methods: ["POST"],
    pattern: '/configuracoes/ambientes',
    tokens: [{"old":"/configuracoes/ambientes","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/ambientes","type":0,"val":"ambientes","end":""}],
    types: placeholder as Registry['configuracoes.ambientes.store']['types'],
  },
  'configuracoes.ambientes.update': {
    methods: ["PUT"],
    pattern: '/configuracoes/ambientes/:id',
    tokens: [{"old":"/configuracoes/ambientes/:id","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/ambientes/:id","type":0,"val":"ambientes","end":""},{"old":"/configuracoes/ambientes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configuracoes.ambientes.update']['types'],
  },
  'configuracoes.ambientes.toggle': {
    methods: ["PATCH"],
    pattern: '/configuracoes/ambientes/:id/toggle',
    tokens: [{"old":"/configuracoes/ambientes/:id/toggle","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/ambientes/:id/toggle","type":0,"val":"ambientes","end":""},{"old":"/configuracoes/ambientes/:id/toggle","type":1,"val":"id","end":""},{"old":"/configuracoes/ambientes/:id/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['configuracoes.ambientes.toggle']['types'],
  },
  'configuracoes.ambientes.destroy': {
    methods: ["DELETE"],
    pattern: '/configuracoes/ambientes/:id',
    tokens: [{"old":"/configuracoes/ambientes/:id","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/ambientes/:id","type":0,"val":"ambientes","end":""},{"old":"/configuracoes/ambientes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configuracoes.ambientes.destroy']['types'],
  },
  'configuracoes.origens.store': {
    methods: ["POST"],
    pattern: '/configuracoes/origens',
    tokens: [{"old":"/configuracoes/origens","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/origens","type":0,"val":"origens","end":""}],
    types: placeholder as Registry['configuracoes.origens.store']['types'],
  },
  'configuracoes.origens.update': {
    methods: ["PUT"],
    pattern: '/configuracoes/origens/:id',
    tokens: [{"old":"/configuracoes/origens/:id","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/origens/:id","type":0,"val":"origens","end":""},{"old":"/configuracoes/origens/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configuracoes.origens.update']['types'],
  },
  'configuracoes.origens.toggle': {
    methods: ["PATCH"],
    pattern: '/configuracoes/origens/:id/toggle',
    tokens: [{"old":"/configuracoes/origens/:id/toggle","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/origens/:id/toggle","type":0,"val":"origens","end":""},{"old":"/configuracoes/origens/:id/toggle","type":1,"val":"id","end":""},{"old":"/configuracoes/origens/:id/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['configuracoes.origens.toggle']['types'],
  },
  'configuracoes.origens.destroy': {
    methods: ["DELETE"],
    pattern: '/configuracoes/origens/:id',
    tokens: [{"old":"/configuracoes/origens/:id","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/origens/:id","type":0,"val":"origens","end":""},{"old":"/configuracoes/origens/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configuracoes.origens.destroy']['types'],
  },
  'configuracoes.campanhas.store': {
    methods: ["POST"],
    pattern: '/configuracoes/campanhas',
    tokens: [{"old":"/configuracoes/campanhas","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/campanhas","type":0,"val":"campanhas","end":""}],
    types: placeholder as Registry['configuracoes.campanhas.store']['types'],
  },
  'configuracoes.campanhas.update': {
    methods: ["PUT"],
    pattern: '/configuracoes/campanhas/:id',
    tokens: [{"old":"/configuracoes/campanhas/:id","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/campanhas/:id","type":0,"val":"campanhas","end":""},{"old":"/configuracoes/campanhas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configuracoes.campanhas.update']['types'],
  },
  'configuracoes.campanhas.toggle': {
    methods: ["PATCH"],
    pattern: '/configuracoes/campanhas/:id/toggle',
    tokens: [{"old":"/configuracoes/campanhas/:id/toggle","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/campanhas/:id/toggle","type":0,"val":"campanhas","end":""},{"old":"/configuracoes/campanhas/:id/toggle","type":1,"val":"id","end":""},{"old":"/configuracoes/campanhas/:id/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['configuracoes.campanhas.toggle']['types'],
  },
  'configuracoes.campanhas.destroy': {
    methods: ["DELETE"],
    pattern: '/configuracoes/campanhas/:id',
    tokens: [{"old":"/configuracoes/campanhas/:id","type":0,"val":"configuracoes","end":""},{"old":"/configuracoes/campanhas/:id","type":0,"val":"campanhas","end":""},{"old":"/configuracoes/campanhas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configuracoes.campanhas.destroy']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
